### PR TITLE
Add command location to plots

### PR DESCRIPTION
**Pull request by DidierRLopes**
Screenshot 2022-03-14 at 15 06 34

### CODE REVIEW

**Review by jmaslek — CHANGES_REQUESTED** [review]
No.

What about tagged on to the Gamestonk Terminal watermark, either next to or as a new one under?

**Comment by DidierRLopes** [comment]
Yea, that's a no. Looks horrible

Screenshot 2022-03-12 at 10 17 39

**Comment by DidierRLopes** [comment]
Another option

image

**Comment by minhhoang1023** [comment]
Looks awesome! Tested with multiple context and working as expected

**Review by jmaslek — APPROVED** [review]

**Pull request merged**
