### PR TITLE
improve usage of timezone in terminal

### PR DESCRIPTION
**Pull request by DidierRLopes**
This PR does 3 main things:
* When loading a ticker, retrieve exchange, timezone, currency and date time of exchange
Screenshot 2022-01-03 at 01 13 15

* Allows the user to specify it's timezone (either through a command or directly in file) and show it, e.g.
Screenshot 2022-01-03 at 02 43 27

* Adding the date time information before the flair (this is a feature flag)
Screenshot 2022-01-03 at 02 43 52

### CODE REVIEW

**Comment by jmaslek** [comment]
Loading the help/? command with the flag now takes way too long.  Can we default the use date time to False?

```
Exchange: NMS (in USD)
```

I would specify the exchange and currency separately. 

```
03 Jan 2022 16:00:16 [America/New_York]
Market: CLOSED

2022 Jan 03, 16:01:17 (✨) /stocks/ $
```

The date reporting is inconsistent.

Using help/? without a ticker has too many spaces

```
Daily Stock: 



    quote       view the current price for a specific stock ticker
```

**Review by jmaslek — CHANGES_REQUESTED** [review]
comments in conversation

**Comment by DidierRLopes** [comment]
@jmaslek I left flag on, but changed to ask it again. The time of additional info won't match, but it doesn't matter because at that time what you've got is the datetime corresponding to the loaded stock. Which makes sense.

**Comment by jmaslek** [comment]
I will leave this to you -- but I think the time looks better if you have just HH:MM instead of HH:MM:SS (also could include a feature flag for 12 or 24 hour clock but that's overkill imo)

**Review by jmaslek — APPROVED** [review]

**Comment by DidierRLopes** [comment]
> I will leave this to you -- but I think the time looks better if you have just HH:MM instead of HH:MM:SS (also could include a feature flag for 12 or 24 hour clock but that's overkill imo)

Agreed, and done!

**Pull request merged**
