### PR TITLE
Fix portfolio : degiro-connector had been upgraded but not the code

### PR DESCRIPTION
**Pull request by Chavithra**
**Reason**
In the requirement files `degiro-connector` was set to a fixed version :

``` toml
degiro-connector = "1.0.0"
```

Somehow today is was upgraded like this :
``` toml
degiro-connector = "^2.0.3"
```

Which seems to make `portfolio` command crash.

**Consequence**
This Pull Request fixes the code to accommodate the version upgrade.

### CODE REVIEW

**Review by piiq — APPROVED** [review]

**Comment by DidierRLopes** [comment]
Screenshot 2021-11-04 at 19 20 21

Next time let's make sure the tests pass before accepting and merging a PR

**Comment by piiq** [comment]
ouch

**Comment by DidierRLopes** [comment]
> ouch

#914 has the lint fix for this anyway :)

**Comment by piiq** [comment]
@Chavithra do you have pre commit hooks enabled

**Pull request merged**
