### PR TITLE
[Bug] Fix degiro controller

### PR DESCRIPTION
**Pull request by juantoca**
Hello there, fellow apes.

I tried to use Degiro's backend to connect to my portfolio. I wanted to see how much I was losing today and couldn't make it work.

I took a look at the codebase and fixed it. I added some improvements to exception handling too.

Edit: I was checking why did this happen and it seems like it was broken on a past refactor. 

TODO: Add a test for the degiro backend

### CODE REVIEW

**Comment by elan17** [comment]
For some reason I cannot add labels and reviewers to the PR :thinking: 

Permissions probably

**Comment by jmaslek** [comment]
> For some reason I cannot add labels and reviewers to the PR :thinking: 
> 
> 
> 
> Permissions probably

I gotchu

Thanks for the fix and welcome aboard!

**Comment by colin99d** [comment]
Hello @elan17! Thank you some much for the contribution. Do you mind doing me a huge favor and removing the @try_except. We are doing a huge refactor right now and once its merged it will not be necessay.

**Comment by elan17** [comment]
Roger roger

**Comment by piiq** [comment]
> I wanted to see how much I was losing today

HODL!

**Comment by jmaslek** [comment]
Thanks @elan17.

I just went though and tried to test the base functionalities.  The login function without an account crashes the entire terminal:

```
Traceback (most recent call last):
  File "/opt/anaconda3/envs/gst/lib/python3.9/site-packages/degiro_connector/trading/actions/action_connect.py", line 98, in get_session_id
    response_raw.raise_for_status()
  File "/opt/anaconda3/envs/gst/lib/python3.9/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://trader.degiro.nl/login/secure/login

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/james/PycharmProjects/GamestonkTerminal/terminal.py", line 401, in <module>
    terminal(sys.argv[1:])
  File "/Users/james/PycharmProjects/GamestonkTerminal/terminal.py", line 346, in terminal
    t_controller.queue = t_controller.switch(an_input)
  File "/Users/james/PycharmProjects/GamestonkTerminal/terminal.py", line 182, in switch
    getattr(
  File "/Users/james/PycharmProjects/GamestonkTerminal/terminal.py", line 281, in call_portfolio
    self.queue = portfolio_controller.menu(self.queue)
  File "/Users/james/PycharmProjects/GamestonkTerminal/gamestonk_terminal/portfolio/portfolio_controller.py", line 498, in menu
    port_controller.queue = port_controller.switch(an_input)
  File "/Users/james/PycharmProjects/GamestonkTerminal/gamestonk_terminal/portfolio/portfolio_controller.py", line 164, in switch
    getattr(
  File "/Users/james/PycharmProjects/GamestonkTerminal/gamestonk_terminal/portfolio/portfolio_controller.py", line 205, in call_bro
    self.queue = bro_controller.menu(self.queue)
  File "/Users/james/PycharmProjects/GamestonkTerminal/gamestonk_terminal/portfolio/brokers/bro_controller.py", line 251, in menu
    bro_controller.queue = bro_controller.switch(an_input)
  File "/Users/james/PycharmProjects/GamestonkTerminal/gamestonk_terminal/portfolio/brokers/bro_controller.py", line 112, in switch
    getattr(
  File "/Users/james/PycharmProjects/GamestonkTerminal/gamestonk_terminal/portfolio/brokers/bro_controller.py", line 154, in call_degiro
    self.queue = degiro_controller.menu(self.queue)
  File "/Users/james/PycharmProjects/GamestonkTerminal/gamestonk_terminal/portfolio/brokers/degiro/degiro_controller.py", line 499, in menu
    degiro_controller.queue = degiro_controller.switch(an_input)
  File "/Users/james/PycharmProjects/GamestonkTerminal/gamestonk_terminal/portfolio/brokers/degiro/degiro_controller.py", line 134, in switch
    self.command_call(known_args, other_args)
  File "/Users/james/PycharmProjects/GamestonkTerminal/gamestonk_terminal/portfolio/brokers/degiro/degiro_controller.py", line 90, in command_call
    raise exception
  File "/Users/james/PycharmProjects/GamestonkTerminal/gamestonk_terminal/portfolio/brokers/degiro/degiro_controller.py", line 79, in command_call
    getattr(
  File "/Users/james/PycharmProjects/GamestonkTerminal/gamestonk_terminal/portfolio/brokers/degiro/degiro_controller.py", line 356, in call_login
    self.__degiro_view.login(ns_parser=ns_parser)
  File "/Users/james/PycharmProjects/GamestonkTerminal/gamestonk_terminal/portfolio/brokers/degiro/degiro_view.py", line 297, in login
    degiro_model.login(credentials=credentials)
  File "/Users/james/PycharmProjects/GamestonkTerminal/gamestonk_terminal/portfolio/brokers/degiro/degiro_model.py", line 253, in login
    self.__trading_api.connect()
  File "/opt/anaconda3/envs/gst/lib/python3.9/site-packages/degiro_connector/core/abstracts/abstract_action.py", line 72, in __call__
    return self.call(*args, **kwargs)
  File "/opt/anaconda3/envs/gst/lib/python3.9/site-packages/degiro_connector/trading/actions/action_connect.py", line 121, in call
    connection_storage.session_id = self.get_session_id(
  File "/opt/anaconda3/envs/gst/lib/python3.9/site-packages/degiro_connector/trading/actions/action_connect.py", line 102, in get_session_id
    raise ConnectionError(e)
ConnectionError: 400 Client Error: Bad Request for url: https://trader.degiro.nl/login/secure/login
```

**Comment by elan17** [comment]
:thinking: 

It seems that is behaviour inherited by the previous implementation. I'll take a look into it in a couple of hours

**Comment by elan17** [comment]
> Thanks @elan17.
> 
> I just went though and tried to test the base functionalities. The login function without an account crashes the entire terminal:
> 
> ```
> Traceback (most recent call last):
>   File "/opt/anaconda3/envs/gst/lib/python3.9/site-packages/degiro_connector/trading/actions/action_connect.py", line 98, in get_session_id
>     response_raw.raise_for_status()
>   File "/opt/anaconda3/envs/gst/lib/python3.9/site-packages/requests/models.py", line 960, in raise_for_status
>     raise HTTPError(http_error_msg, response=self)
> requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://trader.degiro.nl/login/secure/login
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Users/james/PycharmProjects/GamestonkTerminal/terminal.py", line 401, in <module>
>     terminal(sys.argv[1:])
>   File "/Users/james/PycharmProjects/GamestonkTerminal/terminal.py", line 346, in terminal
>     t_controller.queue = t_controller.switch(an_input)
>   File "/Users/james/PycharmProjects/GamestonkTerminal/terminal.py", line 182, in switch
>     getattr(
>   File "/Users/james/PycharmProjects/GamestonkTerminal/terminal.py", line 281, in call_portfolio
>     self.queue = portfolio_controller.menu(self.queue)
>   File "/Users/james/PycharmProjects/GamestonkTerminal/gamestonk_terminal/portfolio/portfolio_controller.py", line 498, in menu
>     port_controller.queue = port_controller.switch(an_input)
>   File "/Users/james/PycharmProjects/GamestonkTerminal/gamestonk_terminal/portfolio/portfolio_controller.py", line 164, in switch
>     getattr(
>   File "/Users/james/PycharmProjects/GamestonkTerminal/gamestonk_terminal/portfolio/portfolio_controller.py", line 205, in call_bro
>     self.queue = bro_controller.menu(self.queue)
>   File "/Users/james/PycharmProjects/GamestonkTerminal/gamestonk_terminal/portfolio/brokers/bro_controller.py", line 251, in menu
>     bro_controller.queue = bro_controller.switch(an_input)
>   File "/Users/james/PycharmProjects/GamestonkTerminal/gamestonk_terminal/portfolio/brokers/bro_controller.py", line 112, in switch
>     getattr(
>   File "/Users/james/PycharmProjects/GamestonkTerminal/gamestonk_terminal/portfolio/brokers/bro_controller.py", line 154, in call_degiro
>     self.queue = degiro_controller.menu(self.queue)
>   File "/Users/james/PycharmProjects/GamestonkTerminal/gamestonk_terminal/portfolio/brokers/degiro/degiro_controller.py", line 499, in menu
>     degiro_controller.queue = degiro_controller.switch(an_input)
>   File "/Users/james/PycharmProjects/GamestonkTerminal/gamestonk_terminal/portfolio/brokers/degiro/degiro_controller.py", line 134, in switch
>     self.command_call(known_args, other_args)
>   File "/Users/james/PycharmProjects/GamestonkTerminal/gamestonk_terminal/portfolio/brokers/degiro/degiro_controller.py", line 90, in command_call
>     raise exception
>   File "/Users/james/PycharmProjects/GamestonkTerminal/gamestonk_terminal/portfolio/brokers/degiro/degiro_controller.py", line 79, in command_call
>     getattr(
>   File "/Users/james/PycharmProjects/GamestonkTerminal/gamestonk_terminal/portfolio/brokers/degiro/degiro_controller.py", line 356, in call_login
>     self.__degiro_view.login(ns_parser=ns_parser)
>   File "/Users/james/PycharmProjects/GamestonkTerminal/gamestonk_terminal/portfolio/brokers/degiro/degiro_view.py", line 297, in login
>     degiro_model.login(credentials=credentials)
>   File "/Users/james/PycharmProjects/GamestonkTerminal/gamestonk_terminal/portfolio/brokers/degiro/degiro_model.py", line 253, in login
>     self.__trading_api.connect()
>   File "/opt/anaconda3/envs/gst/lib/python3.9/site-packages/degiro_connector/core/abstracts/abstract_action.py", line 72, in __call__
>     return self.call(*args, **kwargs)
>   File "/opt/anaconda3/envs/gst/lib/python3.9/site-packages/degiro_connector/trading/actions/action_connect.py", line 121, in call
>     connection_storage.session_id = self.get_session_id(
>   File "/opt/anaconda3/envs/gst/lib/python3.9/site-packages/degiro_connector/trading/actions/action_connect.py", line 102, in get_session_id
>     raise ConnectionError(e)
> ConnectionError: 400 Client Error: Bad Request for url: https://trader.degiro.nl/login/secure/login
> ```

I've already fixed this but I found some more exceptions unhandled. I'll tag this PR as a draft until I fix them.

Also. Sorry for the late response, I had a busy week :sweat:

**Comment by DidierRLopes** [comment]
> > Thanks @elan17.
> > I just went though and tried to test the base functionalities. The login function without an account crashes the entire terminal:
> > ```
> > Traceback (most recent call last):
> >   File "/opt/anaconda3/envs/gst/lib/python3.9/site-packages/degiro_connector/trading/actions/action_connect.py", line 98, in get_session_id
> >     response_raw.raise_for_status()
> >   File "/opt/anaconda3/envs/gst/lib/python3.9/site-packages/requests/models.py", line 960, in raise_for_status
> >     raise HTTPError(http_error_msg, response=self)
> > requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://trader.degiro.nl/login/secure/login
> > 
> > During handling of the above exception, another exception occurred:
> > 
> > Traceback (most recent call last):
> >   File "/Users/james/PycharmProjects/GamestonkTerminal/terminal.py", line 401, in <module>
> >     terminal(sys.argv[1:])
> >   File "/Users/james/PycharmProjects/GamestonkTerminal/terminal.py", line 346, in terminal
> >     t_controller.queue = t_controller.switch(an_input)
> >   File "/Users/james/PycharmProjects/GamestonkTerminal/terminal.py", line 182, in switch
> >     getattr(
> >   File "/Users/james/PycharmProjects/GamestonkTerminal/terminal.py", line 281, in call_portfolio
> >     self.queue = portfolio_controller.menu(self.queue)
> >   File "/Users/james/PycharmProjects/GamestonkTerminal/gamestonk_terminal/portfolio/portfolio_controller.py", line 498, in menu
> >     port_controller.queue = port_controller.switch(an_input)
> >   File "/Users/james/PycharmProjects/GamestonkTerminal/gamestonk_terminal/portfolio/portfolio_controller.py", line 164, in switch
> >     getattr(
> >   File "/Users/james/PycharmProjects/GamestonkTerminal/gamestonk_terminal/portfolio/portfolio_controller.py", line 205, in call_bro
> >     self.queue = bro_controller.menu(self.queue)
> >   File "/Users/james/PycharmProjects/GamestonkTerminal/gamestonk_terminal/portfolio/brokers/bro_controller.py", line 251, in menu
> >     bro_controller.queue = bro_controller.switch(an_input)
> >   File "/Users/james/PycharmProjects/GamestonkTerminal/gamestonk_terminal/portfolio/brokers/bro_controller.py", line 112, in switch
> >     getattr(
> >   File "/Users/james/PycharmProjects/GamestonkTerminal/gamestonk_terminal/portfolio/brokers/bro_controller.py", line 154, in call_degiro
> >     self.queue = degiro_controller.menu(self.queue)
> >   File "/Users/james/PycharmProjects/GamestonkTerminal/gamestonk_terminal/portfolio/brokers/degiro/degiro_controller.py", line 499, in menu
> >     degiro_controller.queue = degiro_controller.switch(an_input)
> >   File "/Users/james/PycharmProjects/GamestonkTerminal/gamestonk_terminal/portfolio/brokers/degiro/degiro_controller.py", line 134, in switch
> >     self.command_call(known_args, other_args)
> >   File "/Users/james/PycharmProjects/GamestonkTerminal/gamestonk_terminal/portfolio/brokers/degiro/degiro_controller.py", line 90, in command_call
> >     raise exception
> >   File "/Users/james/PycharmProjects/GamestonkTerminal/gamestonk_terminal/portfolio/brokers/degiro/degiro_controller.py", line 79, in command_call
> >     getattr(
> >   File "/Users/james/PycharmProjects/GamestonkTerminal/gamestonk_terminal/portfolio/brokers/degiro/degiro_controller.py", line 356, in call_login
> >     self.__degiro_view.login(ns_parser=ns_parser)
> >   File "/Users/james/PycharmProjects/GamestonkTerminal/gamestonk_terminal/portfolio/brokers/degiro/degiro_view.py", line 297, in login
> >     degiro_model.login(credentials=credentials)
> >   File "/Users/james/PycharmProjects/GamestonkTerminal/gamestonk_terminal/portfolio/brokers/degiro/degiro_model.py", line 253, in login
> >     self.__trading_api.connect()
> >   File "/opt/anaconda3/envs/gst/lib/python3.9/site-packages/degiro_connector/core/abstracts/abstract_action.py", line 72, in __call__
> >     return self.call(*args, **kwargs)
> >   File "/opt/anaconda3/envs/gst/lib/python3.9/site-packages/degiro_connector/trading/actions/action_connect.py", line 121, in call
> >     connection_storage.session_id = self.get_session_id(
> >   File "/opt/anaconda3/envs/gst/lib/python3.9/site-packages/degiro_connector/trading/actions/action_connect.py", line 102, in get_session_id
> >     raise ConnectionError(e)
> > ConnectionError: 400 Client Error: Bad Request for url: https://trader.degiro.nl/login/secure/login
> > ```
> 
> I've already fixed this but I found some more exceptions unhandled. I'll tag this PR as a draft until I fix them.
> 
> Also. Sorry for the late response, I had a busy week 😓

No worries @elan17 ! We appreciate your effort towards this, we all been there!

Hopefully tests will pass and we can merge this, thank you! 🙏

**Comment by DidierRLopes** [comment]
Hey @juantoca , any update on this? :)

**Review by Chavithra — APPROVED** [review]
I can run the commands on my side

**Comment by juantoca** [comment]
I'm kind of busy right now to continue the development on the project not gonna lie. But I'm happy that the development was useful. 

If I have more time in the future, I'll try to contribute a bit more. It's a wonderful project.

Happy coding.

**Comment by DidierRLopes** [comment]
> I'm kind of busy right now to continue the development on the project not gonna lie. But I'm happy that the PR was useful.
> 
> If I have more time in the future, I'll try to contribute a bit more. It's a wonderful project.
> 
> Happy coding.

Completely fine! Thanks for your work! 🚀 

And good luck on your projects! 😄

**Pull request merged**
