### PR TITLE
Stock table

### PR DESCRIPTION
**Pull request by colin99d**
# Description

Created a basic table with information over the tickers and looking for feedback. Could not find a way to set a minimum column width, so lots of tickers cause the information to look squished.

# How has this been tested?

Running in Jupyter and Voila.

# Checklist:

- [x] Update [our Hugo documentation](https://gamestonkterminal.github.io/GamestonkTerminal/) following [these guidelines](https://github.com/GamestonkTerminal/GamestonkTerminal/tree/main/website).
- [x] Update our tests following [these guidelines](https://github.com/GamestonkTerminal/GamestonkTerminal/tree/main/tests).
- [x] Make sure you are following our [CONTRIBUTING guidelines](https://github.com/GamestonkTerminal/GamestonkTerminal/blob/main/CONTRIBUTING.md).
- [x] If a feature was added make sure to add it to the corresponding [scripts file](https://github.com/GamestonkTerminal/GamestonkTerminal/tree/main/scripts).

# Others
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My code passes all the checks pylint, flake8, black, ... To speed up development you should run `pre-commit install`.
- [x] New and existing unit tests pass locally with my changes. You can test this locally using `pytest tests/...`.

### CODE REVIEW

**Comment by jmaslek** [comment]
Screen Shot 2022-02-03 at 7 42 05 PM
 other dashboards work fine

**Comment by jmaslek** [comment]
Screen Shot 2022-02-09 at 9 03 27 PM
 
looks nice.  the table is shown twice

**Comment by colin99d** [comment]
> looks nice. the table is shown twice

Fixed!

**Comment by jmaslek** [comment]
So now whenever I type anything into the tickers box, I get an error message in the box:

Screen Shot 2022-02-21 at 8 39 42 PM

**Review by DidierRLopes — APPROVED** [review]

**Pull request merged**
