### PR TITLE
Add dividend calendar from nasdaq

### PR DESCRIPTION
**Pull request by jmaslek**
For the one and only @deeleeramone 

Screen Shot 2022-01-14 at 10 57 26 PM

- [x] tests
- [x] Hugo  
- [x] picture above
- [x] hi Didier  (I couldn't remember the 4th check.  just added get file)

### CODE REVIEW

**Review by colin99d — CHANGES_REQUESTED** [review]
When I don't type in -d I get an infinite wait time. Can it give me more information when I do not do this?

**Comment by jmaslek** [comment]
> When I don't type in -d I get an infinite wait time. Can it give me more information when I do not do this?

So I don't have this happen.  Ill add a short timeout and retry the request is it fails.

**Comment by jmaslek** [comment]
```

2022 Jan 15, 08:55 (✨) /stocks/disc/ $ divcal
No data found.
```

Note this is expected because its a weekend.  I have an idea...

**Comment by jmaslek** [comment]
blah.  the request seems super sporadic even when I add in a timeout

**Review by DidierRLopes — APPROVED** [review]

**Review by colin99d — APPROVED** [review]

**Pull request merged**
