### PR TITLE
Implement keys menu

### PR DESCRIPTION
**Pull request by DidierRLopes**
# Description

Screenshot 2022-02-04 at 04 09 20

# How has this been tested?

* Tested a couple of commands
* Can be used by accessing /keys menu

### CODE REVIEW

**Comment by colin99d** [comment]
It runs `defined, test passed` even if I type in a bad API key. Is that supposed to happen?

**Comment by jmaslek** [comment]
Same.

**Comment by DidierRLopes** [comment]
@colin99d @jmaslek no. I think this is touching in different env files. Need to dig a bit more.

(What happens when u coding at 4am 😄 )

**Comment by DidierRLopes** [comment]
Should be fixed, can u try now? @jmaslek @colin99d

**Comment by colin99d** [comment]
A key of 1 still works for AV. Also, this destroys my old .env with cherished settings. Is there any way around that?

**Comment by DidierRLopes** [comment]
> Sorry the issues I find keep stacking up! Once we get this stuff resolved this will be a great add.
> 
> * A key of 1 still works for AV.
> * This destroys my old .env with cherished settings
> * I think the .env is also now tracked by git
> * I cannot seem to leave the keys menu with q, quit, exit, or cntrl + c

No need to apologize! This is what reviews are for, thanks!

1. I just checked AV doesn't need any key for the type of data we are accessing. I will change the key on .env to be "freekey"
2. I don't think there's much we can do with regards to this. I think we need to swallow this one in order to have better security going forward
3. I added it explicitly to gitignore. Hopefully this will do.
4. Can this be a problem of your setup? I seem to do everything fine:
Screenshot 2022-02-04 at 16 43 32

**Comment by colin99d** [comment]
> > Sorry the issues I find keep stacking up! Once we get this stuff resolved this will be a great add.
> > 
> > * A key of 1 still works for AV.
> > * This destroys my old .env with cherished settings
> > * I think the .env is also now tracked by git
> > * I cannot seem to leave the keys menu with q, quit, exit, or cntrl + c
> 
> No need to apologize! This is what reviews are for, thanks!
> 
> 1. I just checked AV doesn't need any key for the type of data we are accessing. I will change the key on .env to be "freekey"
> 2. I don't think there's much we can do with regards to this. I think we need to swallow this one in order to have better security going forward
> 3. I added it explicitly to gitignore. Hopefully this will do.
> 4. Can this be a problem of your setup? I seem to do everything fine:
> 
Git is still tracking it. We ran into this earlier, which is why the terminal needs a --debug.

**Comment by DidierRLopes** [comment]
> > > Sorry the issues I find keep stacking up! Once we get this stuff resolved this will be a great add.
> > > 
> > > * A key of 1 still works for AV.
> > > * This destroys my old .env with cherished settings
> > > * I think the .env is also now tracked by git
> > > * I cannot seem to leave the keys menu with q, quit, exit, or cntrl + c
> > 
> > 
> > No need to apologize! This is what reviews are for, thanks!
> > 
> > 1. I just checked AV doesn't need any key for the type of data we are accessing. I will change the key on .env to be "freekey"
> > 2. I don't think there's much we can do with regards to this. I think we need to swallow this one in order to have better security going forward
> > 3. I added it explicitly to gitignore. Hopefully this will do.
> > 4. Can this be a problem of your setup? I seem to do everything fine:
> 
> Git is still tracking it. We ran into this earlier, which is why the terminal needs a --debug. The no exit bug must have been me because its gone now.

Yea, if the file exists it will be tracked... Do u have any suggestion?

**Comment by colin99d** [comment]
> > Git is still tracking it. We ran into this earlier, which is why the terminal needs a --debug. The no exit bug must have been me because its gone now.
> 
> Yea, if the file exists it will be tracked... Do u have any suggestion?

This is hacky but python could create the file if it does not exist. Then we never have to track it, Or we could just keep it how things were, and your command adds the keys as they go.

**Comment by DidierRLopes** [comment]
> > > Git is still tracking it. We ran into this earlier, which is why the terminal needs a --debug. The no exit bug must have been me because its gone now.
> > 
> > 
> > Yea, if the file exists it will be tracked... Do u have any suggestion?
> 
> This is hacky but python could create the file if it does not exist. Then we never have to track it, Or we could just keep it how things were, and your command adds the keys as they go.

Ok, let's do that then! Thanks!

**Comment by DidierRLopes** [comment]
> > > Git is still tracking it. We ran into this earlier, which is why the terminal needs a --debug. The no exit bug must have been me because its gone now.
> > 
> > 
> > Yea, if the file exists it will be tracked... Do u have any suggestion?
> 
> This is hacky but python could create the file if it does not exist. Then we never have to track it, Or we could just keep it how things were, and your command adds the keys as they go.

Yup it worked like a glove. Much better!

**Review by colin99d — APPROVED** [review]

**Pull request merged**
