### PR TITLE
Features(crypto): added new commands to defi menu

### PR DESCRIPTION
**Pull request by jose-donato**
This PR adds new commands to defi menu:
* `ldapps` (previously named `llama`): display information about listed dApps on DeFi Llama
image

* `gdapps`: display top dApps (in terms of TVL) grouped by chain [Inspired in [gauss defi project](https://github.com/gauss314/defi)]
image

* `stvl` (previously named `tvl`): displays historical values of the total sum of TVLs from all listed dApps
image

* `dtvl sushiswap,uniswap,pancakeswap,anchor,trader-joe`: displays historical TVL of different dApps.
image

If you have any other better suggestions for the command names lmk

### CODE REVIEW

**Comment by jose-donato** [comment]
`./website/content/cryptocurrency/defi/dtvl/_index.md:9: zlot ==> slot`
anyone know how to fix this? zlot is a name of a protocol and codespell linting gives that warning

**Comment by jmaslek** [comment]
Add it to the code spell exclude (I can't remember if you need to exclude the misspelled word or the word it tries to correct to)

**Comment by jmaslek** [comment]
STVL function:  Takes a while, is there a progress bar we can use?  Also a rogue print
```
2022 Jan 10, 13:55 (✨) /crypto/defi/ $ stvl
200
```

**Comment by jmaslek** [comment]
Couple plots chop off at the bottom.  Example ddvl trader-joe:
Screen Shot 2022-01-10 at 1 58 31 PM

Can fix by doing fig, ax = plt.subplots() then fig.tight_layout(pad=2) at the bottom.  (pad=2 is a preference)

**Comment by jmaslek** [comment]
Not gonna make you change here, but moving forward, I replaced tabulate with a function called `rich_table_from_df`.  Should look into that and start using instead of tabulate.

**Review by jmaslek — CHANGES_REQUESTED** [review]
can you also update .gst file

**Comment by jose-donato** [comment]
> STVL function: Takes a while, is there a progress bar we can use? Also a rogue print
Yea, dtvl also takes a while. I assume that is because there is a lot of calculations being done on Defillama source before sending the output. Will try if i can manage to have some kind of progress. The duration is http request taking too long, not on our end, is this done anywhere else on the terminal already?

> Not gonna make you change here, but moving forward, I replaced tabulate with a function called `rich_table_from_df`. Should look into that and start using instead of tabulate.

Thanks for the review, will fix it asap.

**Comment by jose-donato** [comment]
fixed what you mentioned @jmaslek but looks like it is stuck on windows again

**Review by jmaslek — APPROVED** [review]

**Comment by jose-donato** [comment]
@jmaslek 
```____________ ERROR at teardown of test_get_closing[get_iv_surface] _____________```
this is related to options tests, no clue what happened here

@deeleeramone this last commit fixes `prt` command that you reported on github!

**Comment by DidierRLopes** [comment]
Once #1184 gets merged this will be alright!

**Comment by jose-donato** [comment]
> Once #1184 gets merged this will be alright!

iv surface test was solved but it keeps looping in windows tests

**Pull request merged**
