### PR TITLE
Refactor export functionality concept

### PR DESCRIPTION
**Pull request by DidierRLopes**
@jmaslek what do you think having it like this?

### CODE REVIEW

**Review by jmaslek — APPROVED** [review]
Clever. I like it.

**Comment by DidierRLopes** [comment]
> Clever. I like it.

Which ones did you add it to, so I can fix at least those for now?

**Comment by jmaslek** [comment]
Should just be whichever ba commands have export as a variable

**Comment by DidierRLopes** [comment]
> Should just be whichever ba commands have export as a variable

Does it look good?

**Comment by jmaslek** [comment]
Yes.  Think you got them.  I can add this to my current pr as well

**Pull request merged**
