### PR TITLE
NFT feature opensea collection statistics

### PR DESCRIPTION
**Pull request by jose-donato**
* adds new `stats` command to nft menu

image

### CODE REVIEW

**Comment by jose-donato** [comment]
Should be good now, extra small feature to get the hands dirty with the new tests and improve NFT menu

Thank you for the help and the quick chat @Chavithra 🙌

**Review by Chavithra — APPROVED** [review]
The feature works on my side.

I don't thing it's related to this feature but when I do this I have an infinite loop :
```
(✨) /crypto/nft/ $ statts cryptopunks
```

**Comment by jmaslek** [comment]
Can you add a float format to that table (based on the screenshot you included).

**Comment by jose-donato** [comment]
> Can you add a float format to that table (based on the screenshot you included).

done 👍

**Review by DidierRLopes — CHANGES_REQUESTED** [review]
3 minor things:
Screenshot 2021-12-30 at 02 20 02

Can we have the slurg to be required? You just need a `required=True`, because having "No data found" is misleading.

On the `Creation Date` row that date looks very ugly. Can we have just the day and then either remove the time or put on the next line?

Additionally, since you are at it can you remove `Non Fungible Tokens Menu:` ?

All the rest looks good to me!

**Comment by DidierRLopes** [comment]
Can we add this function in one of the .gst files?

**Review by DidierRLopes — APPROVED** [review]

**Pull request merged**
