### PR TITLE
small improvements in portfolio

### PR DESCRIPTION
**Pull request by devwolff**
improve completer to load ports quicker
use plt.ion in `al` so plot doesnt hang

### CODE REVIEW

**Review by jmaslek — APPROVED** [review]

**Comment by jmaslek** [comment]
@devwolff Can you fix the Mypy issue so I can merge this

**Comment by devwolff** [comment]
> @devwolff Can you fix the Mypy issue so I can merge this

hey @jmaslek, I'm not sure what the issue is. Could you help?

**Comment by jmaslek** [comment]
> > @devwolff Can you fix the Mypy issue so I can merge this
> 
> hey @jmaslek, I'm not sure what the issue is. Could you help?

So just looked.  You do `choices:dict` .  Mypy doesn't understand `dict`.  You need to use typing.Dict (`from typing import Dict`)

**Comment by devwolff** [comment]
> > > @devwolff Can you fix the Mypy issue so I can merge this
> > 
> > 
> > hey @jmaslek, I'm not sure what the issue is. Could you help?
> 
> So just looked. You do `choices:dict` . Mypy doesn't understand `dict`. You need to use typing.Dict (`from typing import Dict`)
> 
> Edit. I don't think that is it. You may need to declare that `self.port_list` is actually a list?
> 
> Final Edit: you can just get rid of the `:dict` in line 70

hey boss, completer doesn't seem to work without `:dict` or `:Dict`. I also tried declaring self.portlist as a list. The test kept failing though

**Comment by devwolff** [comment]
Unsure what the issue is for the controller test. typical noob 🤣

**Comment by jmaslek** [comment]
You can fix the test with:

pytest tests/gamestonk_terminal/portfolio/ --record-mode=rewrite 

And then commit the updated txt file

**Comment by devwolff** [comment]
> You can fix the test with:
> 
> pytest tests/gamestonk_terminal/portfolio/ --record-mode=rewrite
> 
> And then commit the updated txt file

I got 'Exit: Uninstall brotli before running tests' after running pytest

**Comment by jmaslek** [comment]
Yeah there is some weird encoding thing that happens with that.  You can pip uninstall brotli.  Or myself of @colin99d can pr a fix tomorrow

**Comment by devwolff** [comment]
> Yeah there is some weird encoding thing that happens with that. You can pip uninstall brotli. Or myself of @colin99d can pr a fix tomorrow

i uninstall brotli and got this
Screen Shot 2022-01-27 at 12 49 42 PM

**Comment by jmaslek** [comment]
> > Yeah there is some weird encoding thing that happens with that. You can pip uninstall brotli. Or myself of @colin99d can pr a fix tomorrow
> 
> i uninstall brotli and got this Screen Shot 2022-01-27 at 12 49 42 PM

I goofed.  Its pip uninstall brotlipy

**Comment by devwolff** [comment]
> > > Yeah there is some weird encoding thing that happens with that. You can pip uninstall brotli. Or myself of @colin99d can pr a fix tomorrow
> > 
> > 
> > i uninstall brotli and got this Screen Shot 2022-01-27 at 12 49 42 PM
> 
> I goofed. Its pip uninstall brotlipy

I did pip uninstall brotlipy. And it still emits the same error. 
Screen Shot 2022-01-28 at 10 36 25 AM

Maybe it got sth to do with my setup?

**Comment by jmaslek** [comment]
@Chavithra or @colin99d ?

**Comment by colin99d** [comment]
Run pip freeze, unfortunately brotli and brotlipy are the same package with a different pip uninstall.

**Comment by devwolff** [comment]
> Run pip freeze, unfortunately brotli and brotlipy are the same package with a different pip uninstall.

The same issue persists

**Comment by devwolff** [comment]
Perhaps I should close this pr. One of you guys should implement these changes as you guys know what's going on

**Pull request closed without merging**
