### PR TITLE
Fix multiple bugs

### LINKED ISSUE #1461: [Bug] /stocks/load slgg/qa/pick/volume/line - Y-Axis label is on the left, underneath the chart Title.
/stocks/load slgg/qa/pick/volume/line - Y-Axis Label is on the left side of the chart, and is covered up by the Title. Other charts in the terminal have volume labeled as 1M, 1K. This is much more user-friendly than scientific notation. 

Screen Shot 2022-03-09 at 12 01 41 PM

### LINKED ISSUE #1478: [Bug] /stocks/options/oi - there is no legend for the chart.
Missing is the legend for Puts and Calls. 

image

### LINKED ISSUE #1479: [Bug] /stocks/options/hist - a chart is not displayed and the -h flag is not recognized.
The data is great, but is the intention to plot everything there? Perhaps plotting the vol/oi ratio with the high & low plots in a two-scale y-axis set over time is the visual for this data?

```
  hist          plot option history [Tradier]  
```  

```
2022 Mar 12, 22:18 (✨) /stocks/options/ $ hist -h
usage: hist -s STRIKE [-p] [-c CHAIN_ID] [-r] [--source {td,ce}] [-l LIMIT] [-h] [--export {csv,json,xlsx,png,jpg,pdf,svg}]
hist: error: the following arguments are required: -s/--strike
```
```
2022 Mar 12, 22:07 (✨) /stocks/options/ $ hist 30.0
                                           AMC raw data                                           
┏━━━━┳━━━━━━━━━━━━┳━━━━━━┳━━━━━━┳━━━━━━┳━━━━━━━┳━━━━━━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━┓
┃    ┃ Date       ┃ Open ┃ High ┃ Low  ┃ Close ┃ Change ┃ Volume  ┃ Open Interest ┃ Change Since ┃
┡━━━━╇━━━━━━━━━━━━╇━━━━━━╇━━━━━━╇━━━━━━╇━━━━━━━╇━━━━━━━━╇━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━┩
│ 0  │ 2022-03-10 │ 0.72 │ 0.72 │ 0.60 │ 0.64  │ -0.09  │ 147.00  │ 3584.00       │ 0.00         │
├────┼────────────┼──────┼──────┼──────┼───────┼────────┼─────────┼───────────────┼──────────────┤
│ 1  │ 2022-03-09 │ 0.81 │ 0.85 │ 0.70 │ 0.70  │ -0.09  │ 246.00  │ 3613.00       │ -0.09        │
├────┼────────────┼──────┼──────┼──────┼───────┼────────┼─────────┼───────────────┼──────────────┤
│ 2  │ 2022-03-08 │ 0.78 │ 0.98 │ 0.74 │ 0.77  │ -0.03  │ 229.00  │ 3589.00       │ -0.17        │
├────┼────────────┼──────┼──────┼──────┼───────┼────────┼─────────┼───────────────┼──────────────┤
│ 3  │ 2022-03-07 │ 1.06 │ 1.06 │ 0.79 │ 0.79  │ -0.17  │ 191.00  │ 3728.00       │ -0.19        │
├────┼────────────┼──────┼──────┼──────┼───────┼────────┼─────────┼───────────────┼──────────────┤
│ 4  │ 2022-03-04 │ 1.32 │ 1.32 │ 0.95 │ 0.95  │ -0.24  │ 942.00  │ 3661.00       │ -0.33        │
├────┼────────────┼──────┼──────┼──────┼───────┼────────┼─────────┼───────────────┼──────────────┤
│ 5  │ 2022-03-03 │ 1.31 │ 1.40 │ 1.25 │ 1.25  │ -0.07  │ 34.00   │ 3300.00       │ -0.49        │
├────┼────────────┼──────┼──────┼──────┼───────┼────────┼─────────┼───────────────┼──────────────┤
│ 6  │ 2022-03-02 │ 1.42 │ 1.45 │ 1.24 │ 1.34  │ -0.16  │ 109.00  │ 3293.00       │ -0.52        │
├────┼────────────┼──────┼──────┼──────┼───────┼────────┼─────────┼───────────────┼──────────────┤
│ 7  │ 2022-03-01 │ 1.70 │ 1.80 │ 1.48 │ 1.60  │ -0.03  │ 218.00  │ 3294.00       │ -0.60        │
├────┼────────────┼──────┼──────┼──────┼───────┼────────┼─────────┼───────────────┼──────────────┤
│ 8  │ 2022-02-28 │ 1.40 │ 1.70 │ 1.31 │ 1.65  │ 0.31   │ 110.00  │ 3346.00       │ -0.61        │
├────┼────────────┼──────┼──────┼──────┼───────┼────────┼─────────┼───────────────┼──────────────┤
│ 9  │ 2022-02-25 │ 1.48 │ 1.48 │ 1.17 │ 1.26  │ -0.09  │ 140.00  │ 3358.00       │ -0.49        │
├────┼────────────┼──────┼──────┼──────┼───────┼────────┼─────────┼───────────────┼──────────────┤
│ 10 │ 2022-02-24 │ 0.97 │ 1.41 │ 0.97 │ 1.39  │ 0.39   │ 198.00  │ 3265.00       │ -0.54        │
├────┼────────────┼──────┼──────┼──────┼───────┼────────┼─────────┼───────────────┼──────────────┤
│ 11 │ 2022-02-23 │ 1.40 │ 1.40 │ 1.00 │ 1.00  │ -0.16  │ 2215.00 │ 3251.00       │ -0.36        │
├────┼────────────┼──────┼──────┼──────┼───────┼────────┼─────────┼───────────────┼──────────────┤
│ 12 │ 2022-02-22 │ 1.48 │ 1.57 │ 1.10 │ 1.19  │ -0.28  │ 255.00  │ 1623.00       │ -0.46        │
├────┼────────────┼──────┼──────┼──────┼───────┼────────┼─────────┼───────────────┼──────────────┤
│ 13 │ 2022-02-18 │ 1.98 │ 1.98 │ 1.59 │ 1.66  │ -0.13  │ 225.00  │ 1611.00       │ -0.61        │
├────┼────────────┼──────┼──────┼──────┼───────┼────────┼─────────┼───────────────┼──────────────┤
│ 14 │ 2022-02-17 │ 1.80 │ 1.91 │ 1.79 │ 1.91  │ -0.09  │ 3.00    │ 1611.00       │ -0.66        │
├────┼────────────┼──────┼──────┼──────┼───────┼────────┼─────────┼───────────────┼──────────────┤
│ 15 │ 2022-02-16 │ 1.93 │ 2.50 │ 1.93 │ 2.11  │ 0.02   │ 138.00  │ 1611.00       │ -0.70        │
├────┼────────────┼──────┼──────┼──────┼───────┼────────┼─────────┼───────────────┼──────────────┤
│ 16 │ 2022-02-15 │ 1.94 │ 2.06 │ 1.87 │ 2.06  │ 0.11   │ 18.00   │ 1564.00       │ -0.69        │
├────┼────────────┼──────┼──────┼──────┼───────┼────────┼─────────┼───────────────┼──────────────┤
│ 17 │ 2022-02-14 │ 2.03 │ 2.10 │ 1.80 │ 1.85  │ -0.10  │ 125.00  │ 1564.00       │ -0.65        │
├────┼────────────┼──────┼──────┼──────┼───────┼────────┼─────────┼───────────────┼──────────────┤
│ 18 │ 2022-02-11 │ 2.06 │ 2.30 │ 2.05 │ 2.05  │ 0.03   │ 97.00   │ 1595.00       │ -0.69        │
├────┼────────────┼──────┼──────┼──────┼───────┼────────┼─────────┼───────────────┼──────────────┤
│ 19 │ 2022-02-10 │ 1.63 │ 2.83 │ 1.60 │ 2.00  │ 0.09   │ 125.00  │ 1532.00       │ -0.68        │
├────┼────────────┼──────┼──────┼──────┼───────┼────────┼─────────┼───────────────┼──────────────┤
│ 20 │ 2022-02-09 │ 1.49 │ 1.86 │ 1.49 │ 1.83  │ 0.45   │ 198.00  │ 1506.00       │ -0.65        │
├────┼────────────┼──────┼──────┼──────┼───────┼────────┼─────────┼───────────────┼──────────────┤
│ 21 │ 2022-02-08 │ 1.00 │ 1.35 │ 0.96 │ 1.26  │ 0.24   │ 323.00  │ 1474.00       │ -0.49        │
├────┼────────────┼──────┼──────┼──────┼───────┼────────┼─────────┼───────────────┼──────────────┤
│ 22 │ 2022-02-07 │ 1.22 │ 1.22 │ 1.02 │ 1.02  │ -0.16  │ 63.00   │ 1498.00       │ -0.37        │
├────┼────────────┼──────┼──────┼──────┼───────┼────────┼─────────┼───────────────┼──────────────┤
│ 23 │ 2022-02-04 │ 1.20 │ 1.22 │ 1.13 │ 1.22  │ 0.02   │ 125.00  │ 1522.00       │ -0.48        │
├────┼────────────┼──────┼──────┼──────┼───────┼────────┼─────────┼───────────────┼──────────────┤
│ 24 │ 2022-02-03 │ 1.13 │ 1.33 │ 1.13 │ 1.20  │ 0.02   │ 54.00   │ 1554.00       │ -0.47        │
├────┼────────────┼──────┼──────┼──────┼───────┼────────┼─────────┼───────────────┼──────────────┤
│ 25 │ 2022-02-02 │ 1.57 │ 1.61 │ 1.18 │ 1.18  │ -0.25  │ 144.00  │ 1548.00       │ -0.46        │
├────┼────────────┼──────┼──────┼──────┼───────┼────────┼─────────┼───────────────┼──────────────┤
│ 26 │ 2022-02-01 │ 1.65 │ 2.10 │ 1.50 │ 1.57  │ 0.15   │ 92.00   │ 1558.00       │ -0.59        │
├────┼────────────┼──────┼──────┼──────┼───────┼────────┼─────────┼───────────────┼──────────────┤
│ 27 │ 2022-01-31 │ 1.36 │ 1.51 │ 1.32 │ 1.36  │ 0.05   │ 264.00  │ 1579.00       │ -0.53        │
├────┼────────────┼──────┼──────┼──────┼───────┼────────┼─────────┼───────────────┼──────────────┤
│ 28 │ 2022-01-28 │ 1.37 │ 1.40 │ 1.20 │ 1.30  │ -0.05  │ 149.00  │ 1554.00       │ -0.51        │
├────┼────────────┼──────┼──────┼──────┼───────┼────────┼─────────┼───────────────┼──────────────┤
│ 29 │ 2022-01-27 │ 1.65 │ 1.65 │ 1.37 │ 1.37  │ -0.24  │ 52.00   │ 1509.00       │ -0.53        │
├────┼────────────┼──────┼──────┼──────┼───────┼────────┼─────────┼───────────────┼──────────────┤
│ 30 │ 2022-01-26 │ 1.84 │ 2.39 │ 1.78 │ 1.80  │ -0.02  │ 64.00   │ 1497.00       │ -0.64        │
├────┼────────────┼──────┼──────┼──────┼───────┼────────┼─────────┼───────────────┼──────────────┤
│ 31 │ 2022-01-25 │ 1.81 │ 1.92 │ 1.81 │ 1.84  │ -0.12  │ 14.00   │ 1506.00       │ -0.65        │
├────┼────────────┼──────┼──────┼──────┼───────┼────────┼─────────┼───────────────┼──────────────┤
│ 32 │ 2022-01-24 │ 2.07 │ 2.15 │ 1.65 │ 2.08  │ -0.14  │ 331.00  │ 1497.00       │ -0.69        │
├────┼────────────┼──────┼──────┼──────┼───────┼────────┼─────────┼───────────────┼──────────────┤
│ 33 │ 2022-01-21 │ 2.30 │ 2.44 │ 2.02 │ 2.41  │ 0.07   │ 96.00   │ 1245.00       │ -0.73        │
├────┼────────────┼──────┼──────┼──────┼───────┼────────┼─────────┼───────────────┼──────────────┤
│ 34 │ 2022-01-20 │ 2.57 │ 3.15 │ 2.25 │ 2.25  │ -0.10  │ 168.00  │ 1242.00       │ -0.72        │
├────┼────────────┼──────┼──────┼──────┼───────┼────────┼─────────┼───────────────┼──────────────┤
│ 35 │ 2022-01-19 │ 2.87 │ 2.87 │ 2.51 │ 2.51  │ -0.10  │ 173.00  │ 1177.00       │ -0.75        │
├────┼────────────┼──────┼──────┼──────┼───────┼────────┼─────────┼───────────────┼──────────────┤
│ 36 │ 2022-01-18 │ 3.00 │ 3.00 │ 2.46 │ 2.79  │ -0.16  │ 75.00   │ 1023.00       │ -0.77        │
├────┼────────────┼──────┼──────┼──────┼───────┼────────┼─────────┼───────────────┼──────────────┤
│ 37 │ 2022-01-14 │ 3.25 │ 3.45 │ 3.10 │ 3.34  │ -0.02  │ 140.00  │ 833.00        │ -0.81        │
├────┼────────────┼──────┼──────┼──────┼───────┼────────┼─────────┼───────────────┼──────────────┤
│ 38 │ 2022-01-13 │ 4.35 │ 4.35 │ 3.40 │ 3.40  │ -0.18  │ 254.00  │ 833.00        │ -0.81        │
├────┼────────────┼──────┼──────┼──────┼───────┼────────┼─────────┼───────────────┼──────────────┤
│ 39 │ 2022-01-12 │ 4.00 │ 4.35 │ 4.00 │ 4.15  │ -0.01  │ 451.00  │ 858.00        │ -0.85        │
├────┼────────────┼──────┼──────┼──────┼───────┼────────┼─────────┼───────────────┼──────────────┤
│ 40 │ 2022-01-11 │ 4.45 │ 4.61 │ 4.05 │ 4.20  │ -0.07  │ 216.00  │ 582.00        │ -0.85        │
├────┼────────────┼──────┼──────┼──────┼───────┼────────┼─────────┼───────────────┼──────────────┤
│ 41 │ 2022-01-10 │ 4.30 │ 4.50 │ 4.05 │ 4.50  │ -0.04  │ 71.00   │ 426.00        │ -0.86        │
├────┼────────────┼──────┼──────┼──────┼───────┼────────┼─────────┼───────────────┼──────────────┤
│ 42 │ 2022-01-07 │ 4.95 │ 5.50 │ 4.70 │ 4.70  │ 0.00   │ 27.00   │ 362.00        │ -0.86        │
├────┼────────────┼──────┼──────┼──────┼───────┼────────┼─────────┼───────────────┼──────────────┤
│ 43 │ 2022-01-06 │ 4.60 │ 5.00 │ 4.25 │ 4.70  │ 0.03   │ 37.00   │ 341.00        │ -0.86        │
├────┼────────────┼──────┼──────┼──────┼───────┼────────┼─────────┼───────────────┼──────────────┤
│ 44 │ 2022-01-05 │ 5.10 │ 5.15 │ 4.55 │ 4.55  │ -0.22  │ 65.00   │ 317.00        │ -0.86        │
├────┼────────────┼──────┼──────┼──────┼───────┼────────┼─────────┼───────────────┼──────────────┤
│ 45 │ 2022-01-04 │ 6.00 │ 6.00 │ 5.40 │ 5.80  │ -0.13  │ 171.00  │ 268.00        │ -0.89        │
├────┼────────────┼──────┼──────┼──────┼───────┼────────┼─────────┼───────────────┼──────────────┤
│ 46 │ 2022-01-03 │ 7.00 │ 7.00 │ 6.65 │ 6.65  │ -0.01  │ 62.00   │ 111.00        │ -0.90        │
├────┼────────────┼──────┼──────┼──────┼───────┼────────┼─────────┼───────────────┼──────────────┤
│ 47 │ 2021-12-31 │ 7.50 │ 7.50 │ 6.75 │ 6.75  │ -0.10  │ 53.00   │ 0.00          │ -0.91        │
├────┼────────────┼──────┼──────┼──────┼───────┼────────┼─────────┼───────────────┼──────────────┤
│ 48 │ 2021-12-30 │ 7.50 │ 7.50 │ 7.50 │ 7.50  │ 0.00   │ 1.00    │ 0.00          │ -0.91        │
└────┴────────────┴──────┴──────┴──────┴───────┴────────┴─────────┴───────────────┴──────────────┘
```

### PR DESCRIPTION
**Pull request by minhhoang1023**
# Description

### Fixes #1461 
image

### Fixes #1479 
Pasted Graphic 1

image

### Fixes #1478 
image

- [ ] Summary of the change / bug fix.
- [ ] Link # issue, if applicable.
- [ ] Screenshot of the feature or the bug before/after fix, if applicable.
- [ ] Relevant motivation and context. 
- [ ] List any dependencies that are required for this change.

# How has this been tested?

* Please describe the tests that you ran to verify your changes. 
* Provide instructions so we can reproduce. 
* Please also list any relevant details for your test configuration.

# Checklist:

- [ ] Update [our Hugo documentation](https://gamestonkterminal.github.io/GamestonkTerminal/) following [these guidelines](https://github.com/GamestonkTerminal/GamestonkTerminal/tree/main/website).
- [ ] Update our tests following [these guidelines](https://github.com/GamestonkTerminal/GamestonkTerminal/tree/main/tests).
- [ ] Make sure you are following our [CONTRIBUTING guidelines](https://github.com/GamestonkTerminal/GamestonkTerminal/blob/main/CONTRIBUTING.md).
- [ ] If a feature was added make sure to add it to the corresponding [scripts file](https://github.com/GamestonkTerminal/GamestonkTerminal/tree/main/scripts).

# Others
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My code passes all the checks pylint, flake8, black, ... To speed up development you should run `pre-commit install`.
- [ ] New and existing unit tests pass locally with my changes. You can test this locally using `pytest tests/...`.

### CODE REVIEW

**Comment by DidierRLopes** [comment]
For the first one @minhhoang1023 , can we get the M on the label instead of the values. So `Volume [M]`

**Comment by minhhoang1023** [comment]
> label

Tried to change it quickly, but this function is for multiple types of units, e.g. %.

Which results in this:
image

and this:
image

I can work around this, but this would create a bunch of extra code for a very small change. Is it worth it?

**Comment by piiq** [comment]
@minhhoang1023 i would ditch @DidierRLopes request and move on with merging

**Comment by DidierRLopes** [comment]
You can check min/max values on the picture and based on that assign the KMBPT. But let's discuss this offline quickly.

Also, once we do so, can we use square brackets: `[ ]`. E.g. `volume [M]` this has been the convention thus far.

**Comment by minhhoang1023** [comment]
> You can check min/max values on the picture and based on that assign the KMBPT. But let's discuss this offline quickly.

Yes, that's how it's being done right now. What I meant is that we don't want to have any bracket it's a price unit, for example, otherwise, it'd display as an empty bracket like this: `[ ]`. And also decimal point needs to be accounted to, e.g. for percentage vs for volume. So I'd need to account for all different scenarios. 

It's 100% technically possible, and I'm with you that it looks better without the magnitude "KMBPT" being repetitive. The thing is that, we have a similar convention in a lot of other plots - so if we change this, we should also change others. This brings me to the conclusion that changing this would require non-trivial extra code and dev time. I don't mind doing it, but want to make sure that it's worth it.

**Comment by DidierRLopes** [comment]
I see, this was all changed when the matplotlib style refactoring happened..

Can we have the square brackets instead of the curved ones as ylabel? @piiq

**Comment by minhhoang1023** [comment]
It wasn't the square vs round brackets - this can be easily fixed. I meant having the magnitude (KMBPT) in the label vs in the ticker.

**Comment by DidierRLopes** [comment]
> It wasn't the square vs round brackets - this can be easily fixed. I meant having the magnitude (KMBPT) in the label vs in the ticker.

Yes, I know. My suggestion was to not do the ylabel vs ytick thing, but do the square brackets one

**Comment by piiq** [comment]
@DidierRLopes can you clarify, please? Are you proposing the magnitude to appear on y-ticks with square brackets?
like
100 M    ->     100 [M]

**Comment by DidierRLopes** [comment]
@piiq I was talking w.r.t. other plot, so instead of having "Open Interest (1k)" having "Open Interest [1k]". I prefer the square brackets because they are less likely to be used in text, and a curvy one could be used to give additional info. 

E.g. `Gross Domestic Product (GDP) [$ Billion]`

But let's merge this for now.

**Review by DidierRLopes — APPROVED** [review]

**Comment by minhhoang1023** [comment]
@DidierRLopes I'll create an issue to track it. This should be a quick fix.

**Pull request merged**
