### PR TITLE
fix index function in economy

### PR DESCRIPTION
**Pull request by jmaslek**
#1571 
#1570 
fixes bug in index function where date wasnt shown

index0

indexrets

### CODE REVIEW

**Comment by JerBouma** [comment]
Can you add in the update for finvizfinance? From 0.12.2 to 0.13.0? Then the other Economy issue is also fixed. https://pypi.org/project/finvizfinance/

**Comment by jmaslek** [comment]
> @jmaslek can you add in the update for finvizfinance? From 0.12.2 to 0.13.0? Then the other Economy issue is also fixed. https://pypi.org/project/finvizfinance/

@JerBouma done

```
2022 Mar 28, 18:06 (✨) /economy/ $ performance -g country
                                                        Group Performance Data                                                        
┏━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━┳━━━━━━━┳━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┳━━━━━━━┳━━━━━━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━━━┓
┃ Name                 ┃ Week  ┃ Month ┃ 3Month ┃ 6Month ┃ 1Year ┃ YTD   ┃ Recom ┃ AvgVolume (1M) ┃ RelVolume ┃ Change ┃ Volume (1M) ┃
┡━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━╇━━━━━━━╇━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━╇━━━━━━━╇━━━━━━━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━━━━━━━┩
│ Uruguay              │ 0.04  │ 0.09  │ -0.06  │ -0.33  │ -0.11 │ -0.09 │ 1.91  │ 3.48           │ 0.66      │ 0.05   │ 2.30        │
```

**Comment by jmaslek** [comment]
@JerBouma the finviz package now breaks ca functions

**Review by DidierRLopes — APPROVED** [review]

**Comment by JerBouma** [comment]
@jmaslek Why did you close this?

**Comment by jmaslek** [comment]
> @jmaslek Why did you close this? Because updating finviz breaks more than we want?

I threw in the index fix in the other and updating finviz broke more than it fixed.

**Comment by JerBouma** [comment]
Ugh unfortunate.

**Pull request closed without merging**
