### PR TITLE
Update README.md for complete beginner

### PR DESCRIPTION
**Pull request by andrew-app**

### CODE REVIEW

**Comment by aia** [comment]
A complete beginner will probably be on Windows and will not have python.

Best approach is to use Anaconda and Anaconda configs in the repo - https://github.com/GamestonkTerminal/GamestonkTerminal/tree/main/build/conda.

**Comment by DidierRLopes** [comment]
> A complete beginner will probably be on Windows and will not have python.
> 
> Best approach is to use Anaconda and Anaconda configs in the repo - https://github.com/GamestonkTerminal/GamestonkTerminal/tree/main/build/conda.

Should we close this PR? Or refactor it?

**Comment by aia** [comment]
> 
> 
> > A complete beginner will probably be on Windows and will not have python.
> > Best approach is to use Anaconda and Anaconda configs in the repo - https://github.com/GamestonkTerminal/GamestonkTerminal/tree/main/build/conda.
> 
> Should we close this PR? Or refactor it?

I am not sure what value this change adds.

**Comment by DidierRLopes** [comment]
Closing this PR because we don't see that it adds much value to the user as @aia mentioned:
"A complete beginner will probably be on Windows and will not have python."

@andrew-app feel free to comment here if you think otherwise.

**Pull request closed without merging**
