### PR TITLE
Add quarterly contracts to gov menu

### PR DESCRIPTION
**Pull request by DidierRLopes**

### CODE REVIEW

**Review by aia — APPROVED** [review]

**Comment by DidierRLopes** [comment]
@aia is there a reason for us wanting "Squash and merge"?

**Comment by aia** [comment]
> @aia is there a reason for us wanting "Squash and merge"?

I updated a few settings according to best practices as you have noticed :-)

Squash and merge gives us a clear, readable history and easy rollbacks. Many professional projects use either squash-and-merge or rebase-noff-merge. Squash-and-merge is easier from the user's point of view.

**Comment by jmaslek** [comment]
I don't see what the point of the regression is?  You just use the coef[0], but don't plot it or anything...

**Comment by DidierRLopes** [comment]
> > @aia is there a reason for us wanting "Squash and merge"?
> 
> 
> 
> I updated a few settings according to best practices as you have noticed :-)
> 
> 
> 
> Squash and merge gives us a clear, readable history and easy rollbacks. Many professional projects use either squash-and-merge or rebase-noff-merge. Squash-and-merge is easier from the user's point of view.
> 
> 
> 
> As an admin, you always have an override option.
> 
> 

Thanks! Just wanted to understand. Thank you :)

**Comment by DidierRLopes** [comment]
> I don't see what the point of the regression is?  You just use the coef[0], but don't plot it or anything...

I use it to sort the tickers based on their biggest slope. Biggest slope indicates that the contracts amount havie been increasing the most. Once I have those top tickers, I just plot the contracts amounts vs Time.

Does that make sense?

**Comment by jmaslek** [comment]
> I use it to sort the tickers based on their biggest slope. Biggest slope indicates that the contracts amount havie been increasing the most. Once I have those top tickers, I just plot the contracts amounts vs Time.

I see.  yes that makes sense. I was goofing thinking that the coef_[0] is the intercept, so I was confused, but I see now.  Good to merge

**Review by jmaslek — APPROVED** [review]

**Pull request merged**
