### PR TITLE
Complete check on Hugo Documentation

### PR DESCRIPTION
**Pull request by JerBouma**
# Description
In this pull request a complete update of the Documentation is done:

- Checked if command still has same arguments, updated if not.
- Updated description if applicable.
- Created examples for pretty much all functions:
    - If a table was shown, I placed it within ```a code window```.
    - If an image was shown, updated this image.
    - If nothing was shown, made a barebones example of how to use the command.
- Made some updates to the code which was mostly typos or no index showing.

# Checklist:

- [x] Stocks
    - [x] General Options
    - [x] Options
    - [x] Disc
    - [x] sia
    - [x] dps
    - [x] scr
    - [x] ins
    - [x] gov
    - [x] ba
    - [x] ca
    - [x] fa
    - [x] res
    - [x] dd
    - [x] bt
    - [x] qa
    - [x] ta
    - [x] pred
- [x] Crypto
   - [x] General Options
   - [x] disc
   - [x] ov
   - [x] onchain
   - [x] defi
   - [x] nft
   - [x] dd
   - [x] ta
   - [x] pred
- [x] etf
- [x] economy
   - [x] fred
- [x] forex
   - [x] General Options
   - [x] oanda 
- [x] funds
- [x] alternative
   - [x] covid
- [x] portfolio
   - [x] bro 
   - [x] po
- [x] jupyter
   - [x] reports
   - [x] dashboards
- [x] custom (**Skipping Custom since it is getting replaced in https://github.com/GamestonkTerminal/GamestonkTerminal/pull/1353**)

# Others
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My code passes all the checks pylint, flake8, black, ... To speed up development you should run `pre-commit install`.
- [x] New and existing unit tests pass locally with my changes. You can test this locally using `pytest tests/...`.

### CODE REVIEW

**Comment by JerBouma** [comment]
@jmaslek @DidierRLopes 

So, I went through pretty much everything except for:

- Prediction menu, I have a Macbook now with a M1 chip ;)
- Broker menus, I simply have no access to that
- Oanda, no access either
- Twitter functions, couldnt get the API to work

Could you guys cover these items? I got the rest covered.

**Comment by jmaslek** [comment]
@JerBouma I added pred and the twitter functions.  I also don't have panda and the brokers were good.

**Comment by jmaslek** [comment]
@JerBouma I also tried cleaning up the code spell.  I cheated a bit and removed problem lines out of examples because there were some things (like TEH) that could be a common spelling error I didn't want to just ignore

**Review by DidierRLopes — APPROVED** [review]

**Comment by DidierRLopes** [comment]
Thank you guys. Good work on this.

We ready to merge? @JerBouma @jmaslek

**Comment by JerBouma** [comment]
Sounds good to me!

**Pull request merged**
