### PR TITLE
Feature/degiro integration

### PR DESCRIPTION
**Pull request by Chavithra**
Hi,

here are the FEATURES affected by this `Pull Request`:  
1. ADD - command `create`
2. ADD - command `cancel`
3. ADD - command `update`
4. UPDATE - split features into `Model View Controller`

See `README` in `portfolio` part for more information.

### CODE REVIEW

**Comment by jmaslek** [comment]
Upgrade pyupgrade to `2.18.1`

**Comment by Chavithra** [comment]
> Upgrade pyupgrade to `2.18.1`

`pyupgrade` updated some files unrelated to my `Pull Request` : 
- gamestonk_terminal/discovery/marketbeat_view.py
- gamestonk_terminal/fundamental_analysis/business_insider_view.py
- gamestonk_terminal/helper_funcs.py
- gamestonk_terminal/prediction_techniques/arima_view.py
- gamestonk_terminal/residuals_analysis/residuals_model.py

Are this modifications safe ?

**Comment by jmaslek** [comment]
Yeah. If you look at my PR it changed those as well.

**Comment by Chavithra** [comment]
> Yeah. If you look at my PR it changed those as well.

Found some explanation on why `pyupgrade` did that : 
- https://www.python.org/dev/peps/pep-0289/

**Comment by Chavithra** [comment]
For the following one, is it because there is no label in the `Pull Request` ?
- `Pull Request Labels / label (pull_request)`

**Comment by DidierRLopes** [comment]
> For the following one, is it because there is no `Label` in the `Pull Request` ?
> 
> * `Pull Request Labels / label (pull_request)`

It was indeed!

**Comment by aia** [comment]
You want to generate requirements-full.txt too.

```
poetry export -f requirements.txt  -o requirements-full.txt --extras prediction --without-hashes
```

**Comment by DidierRLopes** [comment]
Niceeee! Thank you!!

**Pull request merged**
