### PR TITLE
add fisher transform to ta menu

### PR DESCRIPTION
**Pull request by devwolff**
See if it works for you guys. Let me know if theres anything that should be modified

### CODE REVIEW

**Comment by DidierRLopes** [comment]
Captura de ecrã 2021-08-10, às 23 31 21

Really cool. On the 2nd plot, can I suggest adding:
- A legend for what the lines represent `plt.legend(["legend1", "legend2"]`
- The values of the horizontal lines, or what they represent. Like:

Captura de ecrã 2021-08-10, às 23 33 55

**Comment by DidierRLopes** [comment]
The code looks great, good work there!

**Comment by devwolff** [comment]
Thanks!

**Review by DidierRLopes — APPROVED** [review]
Sweet! Good work! 

Looking forward for more PRs coming from you!!

**Pull request merged**
