### PR TITLE
update incorrect fred key from config file

### LINKED ISSUE #465: [Bug] Wrong API key name for FRED on README.md
**Describe the bug**
On `README.md` under the "API Keys" table, the variable name for the Federal Reserve Economic Data (FRED) is incorrect.  The README lists `GT_FRED_API_KEY` but it needs to be `GT_API_FRED_KEY` as seen in `gamestonk_terminal/config_terminal.py`

**To Reproduce**
1. Go to https://github.com/GamestonkTerminal/GamestonkTerminal/
2. Take a look at the table "API Keys" https://github.com/GamestonkTerminal/GamestonkTerminal/#api-keys

**Additional context**
I was wondering why I kept on getting "Bad Request.  The value for variable api_key is not a 32 character alpha-numeric lower-case string.  Read https://research.stlouisfed.org/docs/api/api_key.html for more information. " error when trying to get any data under `econ` menu.  I know my API key is correct and the format of my `.env` file.  I took a look at the `gamestonk_terminal/config_terminal.py` file and sure enough, the variable name for the FRED API did not match up.

### PR DESCRIPTION
**Pull request by jmaslek**
Fix #465 where the incorrect variable was being imported

### CODE REVIEW

**Comment by jmaslek** [comment]
@DidierRLopes The failing error is once again cvxpy and I noticed that package was updated in your pr yesterday.  Not sure what is causing this exactly.

**Comment by DidierRLopes** [comment]
> @DidierRLopes The failing error is once again cvxpy and I noticed that package was updated in your pr yesterday. Not sure what is causing this exactly.

Weird that this didn't fail in my PR. Let me have a look at this

**Comment by jmaslek** [comment]
@DidierRLopes got it by pinning a bunch of workflows to cvxpy 1.1.12.  Can either merge into main or your pr... up tp you

**Comment by DidierRLopes** [comment]
Thanks a lot!!

**Pull request merged**
