### PR TITLE
add rolling metrics to eda

### PR DESCRIPTION
**Pull request by devwolff**
A small proposal here: Using pandas_ta to include rolling metrics in eda. Though it could be on ta menu, I think it is more suitable to place it in eda as these calculations are definitely not exclusive to ta discourse. Besides, it aligns better with the existing calculations in eda. 

Let me know what you guys think before I go further with this subsection

### CODE REVIEW

**Comment by DidierRLopes** [comment]
I agree with you, and think is a great idea.

I'm away of the laptop today for 7/8h. But once I'm back I'll try these new commands! 😀

**Comment by DidierRLopes** [comment]
In terms of code it looks goods to me!

**Comment by jmaslek** [comment]
I too think this is a good idea.

Could you rename the rolling to rolling_view for now.  

If you wanna be my best friend you can take a look at the recent TA refactoring (I'll also push examples) and change the code so that the argparse is in _controller and there is a _view and _model you can, but I will go ahead and merge this once I confirm nothing strange on my end.  We will be requiring this shortly and you have been moving faster than me :)

**Review by jmaslek — APPROVED** [review]

**Comment by devwolff** [comment]
@DidierRLopes @jmaslek I will help to refactor eda menu this weekend, before we add more materials

**Comment by jmaslek** [comment]
@devwolff No worries. I am almost done with it :)

**Pull request merged**
