### PR TITLE
Add menu option 'quote'

### PR DESCRIPTION
**Pull request by jperkins12**
Adds a main menu option `quote` that shows a table of the current price for a stock.

image

### CODE REVIEW

**Comment by jmaslek** [comment]
So I am not sure of @DidierRLopes opinion, but I would do this through yfinance so that this can be accessed without any api keys.

Also the Open/High/Low/Close depends on time interval, so that could be an option in the parser.

**Comment by jperkins12** [comment]
It could be changed to a yfinance call. I chose AV in this case because it had the `ts.get_quote_endpoint()` function that pulled the latest price data.

**Comment by jperkins12** [comment]
Changed the API to finance

**Comment by jmaslek** [comment]
Thanks. I will test this after market open.  

Can you also update the Readme inside /gamestonkterminal ?

**Comment by jmaslek** [comment]
One other comment.  Can you round all the prices to 2 decimals.  I don't recall if finance returns the prices and whatnot as strings or floats, but if you have them all as floats, you can use `floatfmt=".2f"` in tabulate.

**Comment by jperkins12** [comment]
I can absolutely make all the requested changes. As for the theme, that is standard iTerm + some oh-my-zsh goodness. I'm actually on vscode 😛.

**Comment by jmaslek** [comment]
Sweet looks good to me.  

Make sure your pyupgrade is updraded first then to fix the linter, you can run `pyupgrade --py36-plus gamestonkterminal/main_helper.py`  (or whatever the path is)

**Review by jmaslek — APPROVED** [review]

**Comment by DidierRLopes** [comment]
Really nice! Good work!!

**Pull request merged**
