### PR TITLE
Added coverage to actions

### PR DESCRIPTION
**Pull request by colin99d**
# Description

Added coverage to actions. Thanks @minhhoang1023 for the idea of getting on people's cases about tests.

# How has this been tested?

Saw the thing work on Github.

# Checklist:

- [x] Update [our Hugo documentation](https://gamestonkterminal.github.io/GamestonkTerminal/) following [these guidelines](https://github.com/GamestonkTerminal/GamestonkTerminal/tree/main/website).
- [x] Update our tests following [these guidelines](https://github.com/GamestonkTerminal/GamestonkTerminal/tree/main/tests).
- [x] Make sure you are following our [CONTRIBUTING guidelines](https://github.com/GamestonkTerminal/GamestonkTerminal/blob/main/CONTRIBUTING.md).
- [x] If a feature was added make sure to add it to the corresponding [scripts file](https://github.com/GamestonkTerminal/GamestonkTerminal/tree/main/scripts).

# Others
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My code passes all the checks pylint, flake8, black, ... To speed up development you should run `pre-commit install`.
- [x] New and existing unit tests pass locally with my changes. You can test this locally using `pytest tests/...`.

### CODE REVIEW

**Comment by Chavithra** [comment]
@colin99d Is it possible to have the missing lines in the report ?

How about this one for example :
https://github.com/MishaKav/pytest-coverage-comment

**Comment by colin99d** [comment]
@Chavithra the report looks a lot better once there is an existing coverage.xml file in the main repo (AKA in every PR after this is merged). See this for an example: https://github.com/r0x0d/multi-coverage-demo/pull/1.
The codecov action is also used by 105,000 projects and promises to always be free for open source projects, so I think its a wise choice to stick with it.

**Review by DidierRLopes — APPROVED** [review]

**Comment by jmaslek** [comment]
@colin99d the question was if you can add the graphic like this:
image

**Comment by colin99d** [comment]
It produces a file like this.
Screen Shot 2022-03-21 at 9 10 03 AM

And the link for each file takes you to a breakdown of the file.

**Comment by Chavithra** [comment]
can we have the missing line clickable or at least listed like this ?
120536607-f8df1600-c3ec-11eb-9f49-c6d7571e43ac

**Comment by colin99d** [comment]
> @colin99d Can we have the missing lines clickable or at least listed like this ? 

I think you have to click on the file.

**Pull request merged**
