### PR TITLE
Adding the due diligence context

### PR DESCRIPTION
**Pull request by northern-64bit**
This pr adds the due diligence commands, which don't require api keys, to the discord bot.

### CODE REVIEW

**Comment by jmaslek** [comment]
Awesome job :)

Just curiously, is it possible to print out tables?  Example attached where the output is kinda hard to read in raw text for

Screen Shot 2021-11-11 at 1 34 59 PM
m

**Comment by northern-64bit** [comment]
> Just curiously, is it possible to print out tables? Example attached where the output is kinda hard to read in raw text for


It's not really possible due to discord having different line lengths on different platforms. I've tried to use tabulate, but discord destroyed the formating and made it nearly useless. This is how it looked, but it wouldn't look as good for the command that you mentioned:
image
I'm unsure what is the best option here, but I thought that the implementing way it was in the image could be confusing and unclear. What do you think @jmaslek ?

**Comment by jmaslek** [comment]
>  I'm unsure what is the best option here, but I thought that the implementing way it was in the image could be confusing and unclear. What do you think @jmaslek ?

Im not sure.  But I agree that its better as it is.

**Comment by piiq** [comment]
How does an html payload that's sent with the message look like? Technically we can craft static web pages with a table and have this thing as a message attachment. Discord should process the page and generate some sort of a preview that will be the image part and on click the user can access the tabular data

**Comment by northern-64bit** [comment]
> How does an html payload that's sent with the message look like? Technically we can craft static web pages with a table and have this thing as a message attachment. Discord should process the page and generate some sort of a preview that will be the image part and on click the user can access the tabular data

Yes, this may be a possible solution, but I don't know enough about something like this to implement it. Another possibility is to put the table on a background image and attach the image and add a flag to the commands for raw imput. Now after some testing with it, I've seen that tabulate works if every value in a column has the same length so maybe it's possible to implement a function that makes them the same length. Otherwise we may need to create a "tabulate" specialised for discord.

**Comment by northern-64bit** [comment]
I think I fixed this:
Skärmbild 2021-11-12 110514

**Comment by piiq** [comment]
Since this started, can/should we do something to have the row fit a single line? Like rename the column names and maybe round the decimals?

**Comment by jmaslek** [comment]
> I think I fixed this:
> Skärmbild 2021-11-12 110514


Personally I like everything on one line better.

**Comment by northern-64bit** [comment]
> 
> 
> Since this started, can/should we do something to have the row fit a single line? Like rename the column names and maybe round the decimals?

I agree that it would be good to have everything in one line. There are many other commands that not always return one line. Therefore I think that it would be better to merge this pr and add a note/label with this issue in the discordbot project, since this is a new thing which has nothing to do with the due diligence commands specifically. To continue this conversation we could open a discussion here on github or talk about it in the discord server.

**Comment by piiq** [comment]
> > 
> 
> > 
> 
> > Since this started, can/should we do something to have the row fit a single line? Like rename the column names and maybe round the decimals?
> 
> 
> 
> I agree that it would be good to have everything in one line. There are many other commands that not always return one line. Therefore I think that it would be better to merge this pr and add a note/label with this issue in the discordbot project, since this is a new thing which has nothing to do with the due diligence commands specifically. To continue this conversation we could open a discussion here on github or talk about it in the discord server.

Totally agree. Small incremental changes are the way to go. 
Great job 🙏🙌👍

**Pull request merged**
