### PR TITLE
Discordbot/expiryreactions++

### PR DESCRIPTION
**Pull request by tehcoderer**
+ expiry reaction helper for options
+ added display bot is typing while pulling up options data
+ options IV feature
+ options historical prices feature (tradier token required)
+ added min/max strike to Open interest 
+ options Volume feature with min/max strike 
+ Unusual Options feature
- replaced imgur for + discord.File direct upload
(as imgur tends to not render thumbnails. Like 2 days ago and for about 24hours a week ago)

### CODE REVIEW

**Comment by DidierRLopes** [comment]
@tehcoderer one thing you should do is running `black .` in order to format the code in a similar style to the rest of the repository!

I would also consider running `pre-commit install`. This will make it so all these linter / formatting tests run locally on your machine before you need to push! Which is a life saver really!

Let me know if you need help for any of these!

**Comment by tehcoderer** [comment]
@DidierRLopes Working on it now! Thanks for the help, still new to Python and github 😅. Greatly appreciate it the help

**Comment by tehcoderer** [comment]
@DidierRLopes everything passing till the tests get to pylint and then crashes my VM lol. any suggestions?

**Comment by tehcoderer** [comment]
@DidierRLopes Should be good to go 👍. Ended up running pylint separately by folder

[Workflow](https://github.com/tehcoderer/GamestonkTerminal/runs/4644573375?check_suite_focus=true)

**Comment by DidierRLopes** [comment]
> @DidierRLopes Should be good to go 👍. Ended up running pylint separately by folder
> 
> [Workflow](https://github.com/tehcoderer/GamestonkTerminal/runs/4644573375?check_suite_focus=true)

Thank you! It was holiday in UK the past 2 days so didn't touch a lot the code, will try to have a look at this today! Thanks! 🚀

**Comment by DidierRLopes** [comment]
I think when the user doesn't provide a min and max strike price, we can have a better default window. Plot above is your PR and plot below is the current one.
Screenshot 2021-12-29 at 12 40 28

I absolutely love the choosing the week by an integer instead of typing `2021-12-31`. Can we do 2 additional things:
- When we do it like that, always output what is the day it corresponds to, probably in the title plot.
- Allow to do it when invoking the options menu with `!stocks.opt TSLA 0`

Also, could you add the commands you added to the menu? So if I do: 
Screenshot 2021-12-29 at 12 43 15

I get to see your commands. The `unu` doesn't even require a ticker, so that one can be the number `0` option. Since the `exp` requires a ticker. E.g. If user does `!stocks.opt` they only see `unu`; If user does  `!stocks.opt TSLA` they see `unu` and `exp`; If user does `!stocks.opt TSLA 2021-12-31` or `!stocks.opt TSLA 0` they see all options. On those options we need to reflect the ticker and the expiry date, so replace the `0` by `2021-12-31`.

Let me know if this makes sense :)

Absolutely love the typing detail. Amazing work 🚀

**Review by DidierRLopes — CHANGES_REQUESTED** [review]
Left comment before

**Comment by DidierRLopes** [comment]
Not sure how I feel regarding the asking to expiry date on the `hist`. Although I think is very nice, if we have multiple people using the bot simultaneously, this won't scale very well. 

@piiq @northern-64bit @jmaslek can you give your opinion?

**Comment by tehcoderer** [comment]
> Not sure how I feel regarding the asking to expiry date on the `hist`. Although I think is very nice, if we have multiple people using the bot simultaneously, this won't scale very well.
> 
> @piiq @northern-64bit @jmaslek can you give your opinion?

I totally agree about the default plot, I probably should of tested more tickers haha. 

I worked on your suggestions and requests! I had to head out of the house, but here's what I have so far. 

Screenshot_20211229-112358_Discord
SmartSelect_20211229-112914_Discord
SmartSelect_20211229-112945_Discord
SmartSelect_20211229-113057_Discord

**Comment by tehcoderer** [comment]
> Not sure how I feel regarding the asking to expiry date on the `hist`. Although I think is very nice, if we have multiple people using the bot simultaneously, this won't scale very well.

Not sure what you mean about hist requiring an expriy? It's the individual options history same as from the terminal which also requires an expiry, unless I'm missing something 😅 lol

**Comment by DidierRLopes** [comment]
> > Not sure how I feel regarding the asking to expiry date on the `hist`. Although I think is very nice, if we have multiple people using the bot simultaneously, this won't scale very well.
> > @piiq @northern-64bit @jmaslek can you give your opinion?
> 
> @DidierRLopes I totally agree about the default plot, I probably should of tested more tickers haha.
> 
> I worked on your suggestions and requests! I had to head out of the house, but here's what I have so far.
> 
> Screenshot_20211229-112358_Discord SmartSelect_20211229-112914_Discord SmartSelect_20211229-112945_Discord
> 
> Also just noticed from this image I need to do the same with `hist` and show the expiry on the message title👍🏻. SmartSelect_20211229-113057_Discord
> 
> Disclaimer : I took these on mobile, it's why the spacing is tight.

This is it! Looking very very niceee!!

**Comment by DidierRLopes** [comment]
> > Not sure how I feel regarding the asking to expiry date on the `hist`. Although I think is very nice, if we have multiple people using the bot simultaneously, this won't scale very well.
> 
> Not sure what you mean about hist requiring an expriy? It's the individual options history same as from the terminal which also requires an expiry, unless I'm missing something 😅 lol

Yea, might have been some issue from my side! This looks good, let's merge this baby 😄

**Review by DidierRLopes — APPROVED** [review]
Let's gooooo!! Keep em coming 🔥

**Pull request merged**
