### PR TITLE
Allow Custom Flairs

### PR DESCRIPTION
**Pull request by colin99d**
# Description

Created a custom flair feature flag.

# How has this been tested?

I looked at the new flairs in the terminal.

# Checklist:

- [x] Update [our Hugo documentation](https://gamestonkterminal.github.io/GamestonkTerminal/) following [these guidelines](https://github.com/GamestonkTerminal/GamestonkTerminal/tree/main/website).
- [x] Update our tests following [these guidelines](https://github.com/GamestonkTerminal/GamestonkTerminal/tree/main/tests).
- [x] Make sure you are following our [CONTRIBUTING guidelines](https://github.com/GamestonkTerminal/GamestonkTerminal/blob/main/CONTRIBUTING.md).
- [x] If a feature was added make sure to add it to the corresponding [scripts file](https://github.com/GamestonkTerminal/GamestonkTerminal/tree/main/scripts).

# Others
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My code passes all the checks pylint, flake8, black, ... To speed up development you should run `pre-commit install`.
- [x] New and existing unit tests pass locally with my changes. You can test this locally using `pytest tests/...`.

### CODE REVIEW

**Review by DidierRLopes — CHANGES_REQUESTED** [review]
Can we improve this logic?

I was thinking along the lines of `USE_FLAIR` holding the custom one as well. Basically checking if the flair dictionary had a correspondence in terms of the emoji, and if not the string selected would be the flair used.

I.e. 

if user selects `USE_FLAIR = "(GST to the moon)"` it sees that it doesn't existe on the `flair` dict, and use that directly. If the user uses `rocket` it goes ahead and replace that by the emoji.

And since we are at it, can we rename the keywords to have  `:` at the beginning? Like `:rocket`, `:diamond`, and so on!

**Comment by colin99d** [comment]
Accidentally began renaming the function in this one. Once this gets merged I can work on renaming the rest.

**Comment by CoconutMacaroon** [comment]
@colin99d Maybe I'm wrong, but shouldn't the function rename be a separate PR because it is completely unrelated to this one?

**Comment by DidierRLopes** [comment]
> @colin99d Maybe I'm wrong, but shouldn't the function rename be a separate PR because it is completely unrelated to this one?

You are right @CoconutMacaroon . This was something I requested in #1248, and Colin accidentally committed it in this PR. 

Since it's just renaming a function it should be fine. However, given #1248, what's the merging order you prefer @colin99d ?

**Comment by colin99d** [comment]
> > @colin99d Maybe I'm wrong, but shouldn't the function rename be a separate PR because it is completely unrelated to this one?
> 
> You are right @CoconutMacaroon . This was something I requested in #1248, and Colin accidentally committed it in this PR.
> 
> Since it's just renaming a function it should be fine. However, given #1248, what's the merging order you prefer @colin99d ?

Lets merge this first. I will do the rest of the renaming after merging the other PR with main.

**Review by DidierRLopes — APPROVED** [review]

**Pull request merged**
