### PR TITLE
Decentralized finance

### PR DESCRIPTION
**Pull request by JakubPluta**
Hey there :)

Last couple of days I was working on Decentralized Finance related features. I added few commands for crypto lending protocols, borrowing protocols, total value locked in protocols etc.

At the begining my plan was, to add those features under `discovery menu` - but in the end there were like 5-6 commands that are only related to DeFi, so I created new module -> defi. I am not sure what do you think about it ? 

It's hard to say if in future I will add new features into Defi menu, because today I couldn't find any other source with some cool data in this space. 

So would be great to decide on this point: 

- we move all from this PR into discovery menu
- we leave it as it is -> seperate menu: defi menu

Let me know what do you think 🚀

### CODE REVIEW

**Comment by DidierRLopes** [comment]
Really nice!! Good work!

I'm happy with defi menu to be honest 😄

**Comment by jmaslek** [comment]
I agree with a defi menu

**Review by DidierRLopes — APPROVED** [review]
Nice!! This looks greaaaatt!!!! 🚀 

The only thing I'd say is that you can use the new export capability we added to ba_controller, where you can do it here:
```
parse_known_args_and_warn(parser, other_args, HERE)
```

**Comment by DidierRLopes** [comment]
@jmaslek can we merge this baby?

@jose-donato you gonna like this one :)

**Comment by jmaslek** [comment]
@JakubPluta just ran these and the last three commands gave issues:
```
(✨) (crypto)>(defi)> funding
'NoneType' object has no attribute 'find' 

(✨) (crypto)>(defi)> borrow
'NoneType' object has no attribute 'find' 

(✨) (crypto)>(defi)> lending
'NoneType' object has no attribute 'find' 
```

**Comment by DidierRLopes** [comment]
> @JakubPluta just ran these and the last three commands gave issues:
> 
> ```
> (✨) (crypto)>(defi)> funding
> 'NoneType' object has no attribute 'find' 
> 
> (✨) (crypto)>(defi)> borrow
> 'NoneType' object has no attribute 'find' 
> 
> (✨) (crypto)>(defi)> lending
> 'NoneType' object has no attribute 'find' 
> ```

I've tried these 3 and didn't have issues with them

**Pull request merged**
