### PR TITLE
Update readthedocs creation pipeline #859

### PR DESCRIPTION
**Pull request by piiq**
This PR updates the repo so that the https://gamestonk-terminal.readthedocs.io/ documentation can be automatically built based on the latest codebase.

Changes include:
- Making the `docs/code/` folder to hold files auto generated by `sphinx-apidoc`
- Adding `myst_parser` to dev dependencies
- Updating `poetry.lock` and `requirements` files based on the changes in `pyproject.toml`
- A readme to build the documentation locally

### CODE REVIEW

**Comment by piiq** [comment]
Embedding the developer documentation into the user documentation can be done in multiple ways. More info on this can be found [here](https://docs.readthedocs.io/en/stable/guides/embedding-content.html)

**Comment by DidierRLopes** [comment]
Screenshot 2021-11-01 at 16 40 50

Do you know why do some of these appear empty?

**Comment by piiq** [comment]
> Do you know why do some of these appear empty?
@DidierRLopes Let me check, I think I do

**Comment by piiq** [comment]
Because `tensorflow` is in the extras category of `pyproject.toml` and it's flagged as optional, it does not make it to the `requirements.txt` that's being used by readthedocs builder. When locally I force install tensorflow with `poetry install -E prediction` the most of the ones that appeared empty become OK.

@aia can you advice on this? I create freeze the `requirements.txt` like this:

```bash
poetry export --without-hashes -f requirements.txt --output requirements.txt
poetry export --without-hashes --dev -f requirements.txt --output requirements-full.txt
```

**Comment by aia** [comment]
> readthedocs

Is there a way to get readthedocs to look at requirements-full.txt instead of requirements.txt?

Requirements are generated in the following way:
```
poetry export -f requirements.txt  -o requirements.txt --without-hashes
poetry export -f requirements.txt  -o requirements-full.txt --extras prediction --without-hashes
```

**Comment by piiq** [comment]
> Requirements are generated like so:

Thanks, it worked!

@DidierRLopes They're up 
https://gamestonk-terminal.readthedocs.io/code/gamestonk_terminal.common.prediction_techniques.html#gamestonk-terminal-common-prediction-techniques-arima-view-module

**Review by aia — APPROVED** [review]

**Pull request merged**
