### PR TITLE
Upgrade jupyterlab extension deps to mitigate vulns

### PR DESCRIPTION
**Pull request by piiq**
# Description

Upgrade dependencies to mitigate security vuls.

- upgraded jupyterlab extension deps
- upgraded dep chain to mitigate pillow vulnerability

### CODE REVIEW

**Review by DidierRLopes — APPROVED** [review]

**Comment by DidierRLopes** [comment]
@piiq should we merge this?

**Comment by piiq** [comment]
> @piiq should we merge this?

@DidierRLopes no, i'm still waiting for you to update fear-greed-index on pip 🤷‍♂️

**Comment by DidierRLopes** [comment]
Sorry, thought you just wanted me to merge that PR lol.

Here you go, should be done in a couple of mins!
Screenshot 2022-01-28 at 20 00 47

**Comment by DidierRLopes** [comment]
Screenshot 2022-01-28 at 20 01 22

Done

**Comment by piiq** [comment]
@DidierRLopes if the tests pass - this should be good to go

**Pull request merged**
