### PR TITLE
Add difflib to controllers

### PR DESCRIPTION
**Pull request by jmaslek**
Idk about all y'all but I type the wrong stuff all the time (when prompt is off that is).

I went through the controllers and added a suggestion just like the discord bot.

Screen Shot 2021-11-24 at 5 00 49 PM

### CODE REVIEW

**Comment by DidierRLopes** [comment]
Can we do something like:
- if cutoff > 0.85 or so we just use that command directly
- if cutoff > 0.7 we say "did you mean X?"
- otherwise, we do nothing

**Comment by jmaslek** [comment]
> Can we do something like:
> 
> - if cutoff > 0.85 or so we just use that command directly
> 
> - if cutoff > 0.7 we say "did you mean X?"
> 
> - otherwise, we do nothing

So it seemed that .7 was doing a good job all around.  Should I bump it up a little - maybe .75 then print what the terminal will do - add like a 1 second sleep then just run the command?

**Comment by DidierRLopes** [comment]
> > Can we do something like:
> > 
> > * if cutoff > 0.85 or so we just use that command directly
> > * if cutoff > 0.7 we say "did you mean X?"
> > * otherwise, we do nothing
> 
> So it seemed that .7 was doing a good job all around. Should I bump it up a little - maybe .75 then print what the terminal will do - add like a 1 second sleep then just run the command?

Yup, seems like a good idea to me :)

**Review by aia — APPROVED** [review]

**Review by piiq — APPROVED** [review]

**Comment by DidierRLopes** [comment]
@piiq you should have waited for the changes here. There was still some pendent work and this introduced bug #987.

Next time I'll add the "request changes" flag, I think is better practice.

**Pull request merged**
