### PR TITLE
Open insider menu

### PR DESCRIPTION
**Pull request by DidierRLopes**
Implements several screeners from http://openinsider.com/

I want to add the possibility of a set preset here. As shown here:
Captura de ecrã 2021-07-13, às 02 03 55

But will leave this for another day :)

### CODE REVIEW

**Comment by jmaslek** [comment]
```(✨) (ins)> tist
Length mismatch: Expected axis has 12 elements, new values have 13 elements 
```

**Comment by DidierRLopes** [comment]
> ```python
> ```python
> (✨) (ins)> tist
> Length mismatch: Expected axis has 12 elements, new values have 13 elements 
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> Every other command works for me (df is very large -- but I always run into this)
> ```

Captura de ecrã 2021-07-13, às 21 06 06

tist works for me

**Comment by DidierRLopes** [comment]
> ```python
> ```python
> (✨) (ins)> tist
> Length mismatch: Expected axis has 12 elements, new values have 13 elements 
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> Every other command works for me (df is very large -- but I always run into this)
> ```

Do you have the terminal full screen? Because I'm forcing columns lengths and I can always see it all in same terminal

**Comment by jmaslek** [comment]
> Do you have the terminal full screen? Because I'm forcing columns lengths and I can always see it all in same window

Yeah I'm full screen. Think it's my font. Pretty much happens most of the time.

**Comment by DidierRLopes** [comment]
> > Do you have the terminal full screen? Because I'm forcing columns lengths and I can always see it all in same window
> 
> Yeah I'm full screen. Think it's my font. Pretty much happens most of the time.

That's annoying... What do you think we should do? Do you have any suggestion? 

Re. the `tist` can you try again?

**Review by jmaslek — APPROVED** [review]
`tist` works now (no idea why?)

**Comment by DidierRLopes** [comment]
> `tist` works now (no idea why?)

Weird. Must be from openinsider perhaps?

Do I do something re. column width?

**Comment by jmaslek** [comment]
> Do I do something re. column width?

Nah.  Think you can merge

**Pull request merged**
