### PR TITLE
Add Sentiment Investor API integration

### PR DESCRIPTION
**Pull request by ZeevoX**
[**Sentiment Investor**](https://sentimentinvestor.com/) provide aggregated data for what people are saying about stocks on social media through an API. This pull request integrates the Sentiment Investor API into the Gamestonk Terminal.

### Behavioural Analysis

In the behavioural analysis menu, three new commands have been added.

#### `metrics`

This command presents the four core metrics provided by Sentiment Investor, including AHI, RHI, sentiment and SGP. You can learn more about what these metrics mean on [their website](https://sentimentinvestor.com/learn/metrics).

image

#### `social`

This command presents the number of mentions and the sentiment score for several social media, including Reddit, Twitter, Stocktwits and Yahoo! Finance.

image

#### `historical`

This command plots the selected core metric (sentiment score by default) for the chosen stock for the past seven days, as well as a table with the mean of that metric for each day

image

image

### Stock Discovery

In the stock discovery, two new commands have been added

#### `popular`

This command lists the top `n` (default=10) most popular stocks on social media right now, that is, the ones with the highest Average Hype Index (AHI).

image

#### `emerging`

This command lists the top `n` (default=10) stocks that are being talked about more than usual on social media, that is, the ones with the highest Relative Hype Index (RHI).

image

---

Please let me know what amends you would like to be made to the code, if any.

### CODE REVIEW

**Comment by DidierRLopes** [comment]
Hey @ZeevoX,

This is amazing!! I'll review later today this carefully! We can't be more hyped about this :)

PS: You can add SentimentInvestor to our partnerships in our "About us" section. Below Ops.Syncretism: https://github.com/GamestonkTerminal/GamestonkTerminal/blob/f9375b5ba62ea561b99809f9572033fe6c1054f4/gamestonk_terminal/main_helper.py#L956

**Comment by jmaslek** [comment]
This is looking awesome.  Can you also update the requirements-full.txt and then add a super simple test in main_helper->`check_api_keys()` that verifies the key is supplied

**Comment by jmaslek** [comment]
Also if you could add these functions to the readme in ba (as well as the one in gamestonk_terminal/), with some descriptions of what the data is and where it comes from (feel free to plug the site).

**Comment by DidierRLopes** [comment]
Amazing PR OP. I'm a bit nitpicky, so I hope you don't mind :)

image
Could we have the coloring to the entire row here? Also, after each table/str we usually add a new line to be more easy to digest to the user.

Captura de ecrã 2021-07-23, às 23 09 12

`metrics -h` shouldn't return an error as it did here.

Also, since metrics only has 1 possible argument, you can allow the user to do `metrics AAPL` and not define the `-t` flag. Check how `load` command is implemented in main_helper.

Captura de ecrã 2021-07-23, às 23 08 37
It crashed when I tried social

Captura de ecrã 2021-07-23, às 23 11 27
Could we not have those warnings? Also, probably would be nice to have a red/green color scheme to symbolize the sentiment somehow?

Captura de ecrã 2021-07-23, às 23 12 43
Could we sort the data the other way round, as I think it makes more sense for recent to be on top. Also, a coloring here would be nice.

Could we move emerging and popular functions to behavioural analysis? I'm gonna refactor that menu to reflect if we're looking into a particular stock or trying to find a new one. So as long as you put it in there, then I can refactor it myself :)

Captura de ecrã 2021-07-23, às 23 15 40

The last thing is the description you can use it a bit more in the advantage of Sentiment Investor. Not only by explaining who you are in a few words, but also explaining the meaning of RHI and AHI when these are shown (e.g. emerging/popular). See how finbrain did it for ideas
Captura de ecrã 2021-07-23, às 23 16 31

Although the coding style is a bit different than the one we're used to, I'll let that slide! :p Thank you very much, hope you can go through these quickly, and our users can get Sentiment Investor soon!! And sorry for the extensive review!

**Comment by ZeevoX** [comment]
- Coloring is now applied to the whole row in both `metrics` and `social` commands, and `-t` flag is no longer needed to optionally specify a ticker different to the loaded one. Also, as requested, the table formatting includes an extra line between each metric to help the user digest the information.
  
`metrics NFLX` command output  
  
`social AAPL` command output

- Help menus for all new commands are now more detailed and provide information about what metrics such as AHI and RHI mean and how they are calculated, where relevant.

`metrics --help` command output

- `historical` command output is now sorted by date, starting with most recent, by default. The value for each day is also now colored appropriately.  
  
`historical -t GME RHI` command output  
  
- In addition, the sorting of the table is now configurable through the `--sort` and `--direction` flags.

`historical -t NFLX -s value -d asc RHI` command output

- Non-fatal warning or error messages have been suppressed.

---

I was not able to reproduce the error message you got when running the `social` command. In fact, looking at the stack trace, it appears that the exception you saw was caused by `coinpaprika` and not by the `sentimentinvestor` code. If you are still getting the error message I would be happy to investigate further.

With respect to coloring the graph — this was something that I spent a significant of time working on (admittedly I am no `pyplot` expert) — and I deemed it infeasible to produce a gradient coloration of the graph according to how high or low the sentiment score was. Whereas a binary red-green shading like FinBrain did not seem to add much value to the user experience.

I am also curious as to what you mean by a "coding style [that] is a bit different than the one we're used to" — I had hoped that my code would be easy to understand and maintain — if you would like anything changed in that regard, please do let me know.

**Comment by DidierRLopes** [comment]
Thank you @ZeevoX, for all the changes and comments!

So, I tested Sentiment Investor commands when the user doesn't has a valid API Key, and it crashes badly. Would be good to have a try-catch block to return an error message for the user to go down to sentimentinvestor website to get their key, without crashing the app.

`socials` still retrieves that message. It looks like it flags crypto, but I haven't come across any command that triggered this. I'll investigate this from my side.

Regarding the coding style I meant mostly this architecture:

```
def command_function(l_args, s_ticker, s_interval, df_stock):
    # DEFINE PARSER FOR EACH SI COMMAND
    parser = argparse.ArgumentParser(
        add_help=False,
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        prog="name_command_called",
        description="""
            Description about this command
        """,
    )
    # ADD ARGUMENTS HERE. E.g.:
    parser.add_argument(
        "-o",
        "--offset",
        action="store",
        dest="n_offset",
        type=check_positive,
        default=0,
        help="offset",
    )

    # TRY-CATCH block here in case anything goes wrong to not crash terminal
    try:
        ns_parser = parse_known_args_and_warn(parser, l_args)
        if not ns_parser:
            return

        # CODE

        print("")

    except Exception as e:
        print(e, "\n")
```

**Comment by DidierRLopes** [comment]
So, I found out the culprit. Not sure why it is happening, though.

@JakubPluta I think this line is not used: https://github.com/GamestonkTerminal/GamestonkTerminal/blob/a8417d66ea4149d98b2ffd21643207a415d20534/gamestonk_terminal/cryptocurrency/coinpaprika/coinpaprika_view.py#L73

and it's the one that gives me an issue on ba/social. Are we ok to comment it for now, to be able to merge this PR?

**Comment by JakubPluta** [comment]
Hi @DidierRLopes, very strange. But anyway you can just remove it. As I checked it won't break anything. Later will check what was the reason.

**Comment by ZeevoX** [comment]
Thank you, @DidierRLopes, for your work in reviewing and debugging this pull request. I've commented the line that was throwing the error message, but I can't really test whether that helped because I didn't get an error message in the first place :thinking:  

I've adopted the `try`-`except` structure for commands and now the absence of API credentials or presence of invalid ones throws an appropriate error message. 

image

**Review by aia — APPROVED** [review]

**Comment by aia** [comment]
Great work! Thank you @ZeevoX.

**Comment by DidierRLopes** [comment]
> Thank you, @DidierRLopes, for your work in reviewing and debugging this pull request. I've commented the line that was throwing the error message, but I can't really test whether that helped because I didn't get an error message in the first place 🤔
> 
> I've adopted the `try`-`except` structure for commands and now the absence of API credentials or presence of invalid ones throws an appropriate error message.
> 
> image

Amazing @ZeevoX !!! Let's get these tests passing, and merge this!

**Pull request merged**
