### PR TITLE
add settings menu

### PR DESCRIPTION
**Pull request by DidierRLopes**
# Description

- Add settings menu
Screenshot 2022-02-05 at 03 20 44

# How has this been tested?

- Changing values and seeing them being changed on .env and then loaded properly when exiting terminal.

### CODE REVIEW

**Comment by colin99d** [comment]
Menu looks super cool, how do I access it?

**Comment by jmaslek** [comment]
Ummmmmm
```
(gst) james@Jamess-MBP GamestonkTerminal % python terminal.py settings
usage: terminal {update,about,keys,tz,stocks,economy,crypto,portfolio,forex,etf,jupyter,funds,alternative,custom,cls,home,h,?,help,q,quit,..,exit,r,reset}
terminal: error: argument cmd: invalid choice: 'settings' (choose from 'update', 'about', 'keys', 'tz', 'stocks', 'economy', 'crypto', 'portfolio', 'forex', 'etf', 'jupyter', 'funds', 'alternative', 'custom', 'cls', 'home', 'h', '?', 'help', 'q', 'quit', '..', 'exit', 'r', 'reset')

The command 'settings' doesn't exist on the / menu
```

**Comment by colin99d** [comment]
> Ummmmmm
> 
> ```
> (gst) james@Jamess-MBP GamestonkTerminal % python terminal.py settings
> usage: terminal {update,about,keys,tz,stocks,economy,crypto,portfolio,forex,etf,jupyter,funds,alternative,custom,cls,home,h,?,help,q,quit,..,exit,r,reset}
> terminal: error: argument cmd: invalid choice: 'settings' (choose from 'update', 'about', 'keys', 'tz', 'stocks', 'economy', 'crypto', 'portfolio', 'forex', 'etf', 'jupyter', 'funds', 'alternative', 'custom', 'cls', 'home', 'h', '?', 'help', 'q', 'quit', '..', 'exit', 'r', 'reset')
> 
> The command 'settings' doesn't exist on the / menu
> ```

I am requesting a pre-commit hook. No commits after 1 am.

**Comment by piiq** [comment]
> I am requesting a pre-commit hook. No commits after 1 am.

I agree!

**Comment by DidierRLopes** [comment]
Leave my sleeping schedule alone 😴

**Review by colin99d — APPROVED** [review]

**Pull request merged**
