### PR TITLE
Fix FRED API KEY name #465

### PR DESCRIPTION
**Pull request by DidierRLopes**
This should supersede #466

### CODE REVIEW

**Comment by DidierRLopes** [comment]
@aia do you know what's happening here? Me and @jmaslek are struggling to find out why the test fails

**Comment by aia** [comment]
```
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
```

This is your problem. We have seen it before.

You want to figure out the correct version here:
https://github.com/GamestonkTerminal/GamestonkTerminal/blob/main/.github/workflows/windows.yml#L55

**Comment by aia** [comment]
https://github.com/GamestonkTerminal/GamestonkTerminal/issues/348#issuecomment-822872464

**Comment by DidierRLopes** [comment]
> #348 (comment)

You're right. @jmaslek already solved this. Thanks both of you :)

**Pull request merged**
