### PR TITLE
Yup, incoming NFT context

### PR DESCRIPTION
**Pull request by DidierRLopes**
Uses this website https://nftcalendar.io/ from a video recommended by @aia

### CODE REVIEW

**Comment by piiq** [comment]
Lalalalalala 💃
Lalalalalala 🕺

**Comment by piiq** [comment]
@DidierRLopes I think you forgot to enable the context in the main menu. Or was it on purpose so that the feature is like a placeholder or easter egg?

**Comment by DidierRLopes** [comment]
> @DidierRLopes I think you forgot to enable the context in the main menu. Or was it on purpose so that the feature is like a placeholder or easter egg?

Nahh, I forgot to commit that file! 🙄

**Comment by jose-donato** [comment]
@DidierRLopes Just tried it locally. All four features working as expected.
Since they are all related to drops we could simplify and call it `drops` and then pass arguments `drops --upcoming` or `drops --ongoing`. What do you think about that?

**Comment by DidierRLopes** [comment]
> @DidierRLopes Just tried it locally. All four features working as expected.
> Since they are all related to drops we could simplify and call it `drops` and then pass arguments `drops --upcoming` or `drops --ongoing`. What do you think about that?

I agree in doing that refactoring later on, I think for now is best to have more commands since this menu is just getting started 😋

**Review by piiq — APPROVED** [review]

**Review by jose-donato — APPROVED** [review]
Everything looks good to me!

**Pull request merged**
