### PR TITLE
Fix visualise sia metric 

### PR DESCRIPTION
**Pull request by minhhoang1023**
The bug is raised in this [issue](https://github.com/GamestonkTerminal/GamestonkTerminal/issues/1387). This is due to the page change its HTML classes.

Fix:
- Update HTML classes

image

# Description

- [ ] Summary of the change / bug fix.
- [ ] Link # issue, if applicable.
- [ ] Screenshot of the feature or the bug before/after fix, if applicable.
- [ ] Relevant motivation and context. 
- [ ] List any dependencies that are required for this change.

# How has this been tested?

* Please describe the tests that you ran to verify your changes. 
* Provide instructions so we can reproduce. 
* Please also list any relevant details for your test configuration.

# Checklist:

- [ ] Update [our Hugo documentation](https://gamestonkterminal.github.io/GamestonkTerminal/) following [these guidelines](https://github.com/GamestonkTerminal/GamestonkTerminal/tree/main/website).
- [ ] Update our tests following [these guidelines](https://github.com/GamestonkTerminal/GamestonkTerminal/tree/main/tests).
- [ ] Make sure you are following our [CONTRIBUTING guidelines](https://github.com/GamestonkTerminal/GamestonkTerminal/blob/main/CONTRIBUTING.md).
- [ ] If a feature was added make sure to add it to the corresponding [scripts file](https://github.com/GamestonkTerminal/GamestonkTerminal/tree/main/scripts).

# Others
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My code passes all the checks pylint, flake8, black, ... To speed up development you should run `pre-commit install`.
- [ ] New and existing unit tests pass locally with my changes. You can test this locally using `pytest tests/...`.

### CODE REVIEW

**Comment by minhhoang1023** [comment]
Noticed that this particular plot doesn't follow our style. Will address this in a separate PR

**Review by piiq — APPROVED** [review]

**Comment by DidierRLopes** [comment]
Screenshot 2022-02-21 at 13 59 49

I am getting this here 😬

**Comment by piiq** [comment]
@DidierRLopes The tests fail after the update with main. I haven't yet figured out how to fix them

**Comment by piiq** [comment]
@minhhoang1023 updating the cassettes seems to fix tests locally. Tests pass now

@DidierRLopes 
image

**Comment by minhhoang1023** [comment]
@piiq tests now failing again, due to the `pandas_market_calendars` while it passed locally. Should due to version mismatch - how can we update the cicd pipeline?

**Pull request merged**
