### PR TITLE
Add autosave option when the terminal prints a table.

### PR DESCRIPTION
**Pull request by jbushago**
# Description
Previously, there was no easy way to save the output of a command that produces a table. This PR introduces an autosave setting which automatically saves the output of tables (with their names and timestamps) in a folder.

@cweckerl implemented the functionality and I wrote the tests.

# How has this been tested?
Seven new tests were added to the repository which test previously untested files. All functionality of the feature is tested in the unit tests. These tests are automatically included in the `pytest` pipeline.

### CODE REVIEW

**Comment by jbushago** [comment]
Disregard this, it was meant to be a PR to my fork.

**Comment by DidierRLopes** [comment]
Hey @jbushago, why not doing this PR to the main repo?

We are very happy to have new contributions, and are always looking for ways to add more value to the people who use our platform! 😄

**Comment by jbushago** [comment]
Thanks for the warm intro :). Let us at least clean it up first!

**Comment by DidierRLopes** [comment]
Hey @jbushago and @cweckerl,

Sorry, only saw your reply now!

Was about to let you guys know that I added 2 new features that can be of your interest:

- Customisable export folder (saved as environment variable between spinning terminal again)
- Customisable exported data filenames

Quick example of what to expect:

Screenshot 2022-03-17 at 02 33 00

Let me know if there's something else you would like!

**Pull request closed without merging**
