### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by DidierRLopes**

### CODE REVIEW

**Review by jmaslek — APPROVED** [review]

**Review by colin99d — APPROVED** [review]
If this works can we get details on you did? I have been trying everything and cannot get my DCF tests to pass (they work on my personal computer, but not on Github Actions).

**Comment by DidierRLopes** [comment]
> If this works can we get details on you did? I have been trying everything and cannot get my DCF tests to pass (they work on my personal computer, but not on Github Actions).

Also failing here, and locally all fine 😞 very frustrating.

**Comment by colin99d** [comment]
> > If this works can we get details on you did? I have been trying everything and cannot get my DCF tests to pass (they work on my personal computer, but not on Github Actions).
> 
> Also failing here, and locally all fine 😞 very frustrating.

`WARNING  bs4.dammit:dammit.py:2858 Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.`
I was getting the above error. My best guess is that they are using different file formats on Mac and Linux. I tried firing up Ubuntu on UTM to problem solve but did not have any luck.

**Comment by DidierRLopes** [comment]
> > > If this works can we get details on you did? I have been trying everything and cannot get my DCF tests to pass (they work on my personal computer, but not on Github Actions).
> > 
> > 
> > Also failing here, and locally all fine 😞 very frustrating.
> 
> `WARNING bs4.dammit:dammit.py:2858 Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.` I was getting the above error. My best guess is that they are using different file formats on Mac and Linux. I tried firing up Ubuntu on UTM to problem solve but did not have any luck.

Do you have that brotly lib or wtv on ur machine?

**Comment by colin99d** [comment]
> brotly

Just removed brotly. Good catch.

**Comment by DidierRLopes** [comment]
> > brotly
> 
> Just removed brotly. Good catch.

Would be good to understand where it came from. Or how to prevent adding it. This is one of the things @Chavithra told me that we need to solve in the future!

**Comment by colin99d** [comment]
> Would be good to understand where it came from. Or how to prevent adding it. This is one of the things @Chavithra told me that we need to solve in the future!

Can we use [this](https://docs.pytest.org/en/latest/how-to/writing_hook_functions.html) to create pre-pytest hooks that check for brotly and wtv? @jmaslek you inspired a lot today.

**Comment by DidierRLopes** [comment]
> this

Deploy @colin99d in the field. Over! 😄

**Comment by DidierRLopes** [comment]
I think this will pass 🥳 

We will see green again! My portfolio is red enough as is, no need for red PRs 🤣

**Pull request merged**
