### PR TITLE
DISC Cleanup

### PR DESCRIPTION
**Pull request by jmaslek**
Addressed comments in #1052 

I decided to delete market view since it is paywalled

@Chavithra make sure @DidierRLopes is good before merging.

Not sure what to do re: seeking alpha verification

### CODE REVIEW

**Comment by DidierRLopes** [comment]
I'm happy with this.

I've tested Seeking Alpha commands and all work. Do you mean this "latest"?

If so I'm happy with removing this argument and just call this function `trending_news` or so.

```
def news(news_type: str, article_id: int, num: int, start_date: datetime, export: str):
    """Prints the latest news article list. [Source: Seeking Alpha]

    Parameters
    ----------
    news_type: str
        Select between 'latest' or 'trending'
    article_id: int
        Article ID. If -1, none is selected
    num: int
        Number of articles to display. Only used if article_id is -1.
    start_date : datetime
        Date from when to get articles dates. Only used if article_id is -1.
    export : str
        Export dataframe data to csv,json,xlsx file
    """
    # User wants to see all latest news
    if article_id == -1:
        if news_type == "latest":
            articles = seeking_alpha_model.get_article_list(start_date, num)
```

**Review by DidierRLopes — COMMENTED** [review]
lgtm, let's merge once the test is fixed

**Comment by Chavithra** [comment]
This should fix the current issue with tests :
```python
pytest tests/gamestonk_terminal/stocks/government/test_quiverquant_view.py -k test_call_func --record-mode=rewrite
```

**Review by DidierRLopes — APPROVED** [review]

**Comment by Chavithra** [comment]
That's a mystery to me because the changes here don't seem to impact  `Quiverquant View`.

One think is sure the generated `txt` files now match the `cassettes` content.

**Pull request merged**
