### PR TITLE
Improve labelling and some minor fixes

### PR DESCRIPTION
**Pull request by JerBouma**
# Description
The labelling was a bit off and confusing for the user. E.g. some units were reported in "Thousands" but the actual values were also over >1,000 (thus millions) which was not properly corrected. Next to that, labelling of different types also wasn't included. Lastly, the -cc parameter for macro also adjusted non-currency values.

Before:
image

After:
image

# How has this been tested?
Tests adjusted for new units parameter. All run perfectly.

# Checklist:

- [x] Update [our Hugo documentation](https://gamestonkterminal.github.io/GamestonkTerminal/) following [these guidelines](https://github.com/GamestonkTerminal/GamestonkTerminal/tree/main/website).
- [x] Update our tests following [these guidelines](https://github.com/GamestonkTerminal/GamestonkTerminal/tree/main/tests).
- [x] Make sure you are following our [CONTRIBUTING guidelines](https://github.com/GamestonkTerminal/GamestonkTerminal/blob/main/CONTRIBUTING.md).
- [x] If a feature was added make sure to add it to the corresponding [scripts file](https://github.com/GamestonkTerminal/GamestonkTerminal/tree/main/scripts).

# Others
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My code passes all the checks pylint, flake8, black, ... To speed up development you should run `pre-commit install`.
- [x] New and existing unit tests pass locally with my changes. You can test this locally using `pytest tests/...`.

### CODE REVIEW

**Comment by JerBouma** [comment]
@jmaslek Could you briefly look at this one? Nothing too exciting but this is the "right way".

**Review by jmaslek — APPROVED** [review]

**Comment by jmaslek** [comment]
@JerBouma why is this now taking the full 6 hours....

**Comment by JerBouma** [comment]
@jmaslek Pretty much means it crashed but we don't have anything build in that stops the task and generates an error. But why these tests stop working. I dunno.

**Comment by jmaslek** [comment]
@JerBouma fixed it :D

**Pull request merged**
