### PR TITLE
Upgrade Economy Menu

### PR DESCRIPTION
**Pull request by JerBouma**
# Description
This PR updates the Economy menu. It add in a bunch of macro data from EconDB and FRED and allows the user to plot any data points together in a multi-axes graph. This makes understanding relationship between macro indicators far easier.

Some examples:
```
2022 Mar 15, 07:20 (✨) /economy/ $ macro -p CONF -c Netherlands Germany France -s 2005-01-01 -e 2022-01-01
```
Figure_1

```
2022 Mar 15, 07:09 (✨) /economy/ $ fred T10Y2Y DFII10 -s 2019-01-01 -e 2022-01-01
```
fred

```
2022 Mar 15, 07:43 (✨) /economy/ $ macro -p URATE CONF -c France Italy -s 2005-01-01 -st
2022 Mar 15, 07:45 (✨) /economy/ $ plot -s
                   Options available to plot                    
┏━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Command ┃ Options                                            ┃
┡━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ macro   │ France_URATE, France_CONF, Italy_URATE, Italy_CONF │
└─────────┴────────────────────────────────────────────────────┘

2022 Mar 15, 07:43 (✨) /economy/ $ plot -y1 France_URATE Italy_URATE -y2 France_CONF Italy_CONF
```
Figure_1

```
2022 Mar 15, 07:39 (✨) /economy/ $ treasury -m 1y 10y -s 2005-01-01 -st
  2022 Mar 15, 07:40 (✨) /economy/ $ index sp500 -s 2005-01-01 -st
2022 Mar 15, 07:40 (✨) /economy/ $ plot -y1 sp500 -y2 Nominal_1-year Nominal_10-year
```
Figure_2

# How has this been tested?

Created tests for every new command added.

# Checklist:

- [x] Update [our Hugo documentation](https://gamestonkterminal.github.io/GamestonkTerminal/) following [these guidelines](https://github.com/GamestonkTerminal/GamestonkTerminal/tree/main/website).
- [x] Update our tests following [these guidelines](https://github.com/GamestonkTerminal/GamestonkTerminal/tree/main/tests).
- [x] Make sure you are following our [CONTRIBUTING guidelines](https://github.com/GamestonkTerminal/GamestonkTerminal/blob/main/CONTRIBUTING.md).
- [x] If a feature was added make sure to add it to the corresponding [scripts file](https://github.com/GamestonkTerminal/GamestonkTerminal/tree/main/scripts).

# Others
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My code passes all the checks pylint, flake8, black, ... To speed up development you should run `pre-commit install`.
- [x] New and existing unit tests pass locally with my changes. You can test this locally using `pytest tests/...`.

### CODE REVIEW

**Comment by JerBouma** [comment]
Just some notes how the country codes were filtered. Used: https://countrycode.org/ and exported to Excel to create Dictionaries for (see attached). Then ran this code to check which country codes existed and which did not. If they didn't exist, they got deleted. This results in data for 85 countries.

```
for country in copy.copy(COUNTRY_CODES):
    try:
        pd.read_csv(
            f'https://www.econdb.com/api/series/RGDP{COUNTRY_CODES[country]}/?format=csv',
            index_col='Date', parse_dates=['Date'])
    except urllib.error.HTTPError:
        print(country)
        del COUNTRY_CODES[country]
 ```
[Country Codes.xlsx](https://github.com/GamestonkTerminal/GamestonkTerminal/files/8197679/Country.Codes.xlsx)

**Comment by JerBouma** [comment]
@jmaslek Feel free to have a look. Tests are still broken though (even though they pass locally just fine). If you could take a look at that as well go ahead.

**Comment by jmaslek** [comment]
ignore the commit name lol.  I just re recorded all Econ things to see if something was missing....

**Comment by JerBouma** [comment]
Graphs now have the legend outside of the plot. This makes more sense since the legends can be rather large sometimes.

Screenshot 2022-03-16 at 10 03 44

**Comment by jmaslek** [comment]
@JerBouma I started to work on the prediction part, but it will probably be a day or 2.  You can either comment it out for now or we just wait til I do it.  Up to you.

**Comment by JerBouma** [comment]
> @JerBouma I started to work on the prediction part, but it will probably be a day or 2. You can either comment it out for now or we just wait til I do it. Up to you.

@jmaslek We can wait, no priority to push this right away.

**Comment by JerBouma** [comment]
Fixed the wrapping of legends.
Screenshot 2022-03-17 at 09 18 36

As well as titles
Figure_1

**Review by jmaslek — APPROVED** [review]

**Review by jmaslek — CHANGES_REQUESTED** [review]
I need to add the pred documentation

**Comment by jmaslek** [comment]
@JerBouma added pred AND qa with documentation.  lmk if there's anything you want me to change before we merge this.

**Comment by JerBouma** [comment]
All looks good to me. Nice addition to have qa in there as well. Ready to merge :)

**Review by jmaslek — APPROVED** [review]

**Pull request merged**
