### PR TITLE
Fix discordbot requirements

### PR DESCRIPTION
**Pull request by DidierRLopes**

### CODE REVIEW

**Comment by DidierRLopes** [comment]
@piiq #1108 fixes it

**Comment by piiq** [comment]
@DidierRLopes Oh, snap! I've appled a fix also ...

**Comment by piiq** [comment]
We can actually close this without merging. The ghpages are fixed by #1108 and the requirements.txt were updated with the general deps upgrade.
@DidierRLopes Closing this without merging and resolving?

**Comment by DidierRLopes** [comment]
This fix is very specific for the discordbot requirements, it actually doesn't touch the main ones. This is how I managed to have the bot running on Heroku. Basically having the same normal requirements.txt + discord + imgur and so

**Comment by piiq** [comment]
AFAK the deps upgrade addresses the issues related to heroku.
The discord bot `requirements.txt` has been generated with:
```bash
poetry export \
       -f requirements.txt \
       --dev \
       -E discord \
       --without-hashes \
       --output discordbot/requirements.txt
```

**Comment by DidierRLopes** [comment]
> AFAK the deps upgrade addresses the issues related to heroku. The discord bot `requirements.txt` has been generated with:
> 
> ```shell
> poetry export \
>        -f requirements.txt \
>        --dev \
>        -E discord \
>        --without-hashes \
>        --output discordbot/requirements.txt
> ```

Ok, closing this then! Thanks!

**Pull request closed without merging**
