### PR TITLE
Discord Bot: Adding Government Commands

### PR DESCRIPTION
**Pull request by northern-64bit**

### CODE REVIEW

**Comment by jmaslek** [comment]
Make sure that you correct the bugs I fixed the other day (#948 and #952 )

First comment I have here about the tables again.  Not sure if @DidierRLopes has any input about how to format them


Screen Shot 2021-11-17 at 2 53 05 PM

**Comment by northern-64bit** [comment]
> Make sure that you correct the bugs I fixed the other day (#948 and #952 )

I didn't realise that this got fixed. I'll fix this soon :). I haven't found a solution for the table issue yet, but there are some options on the table. Currently I'm thinking about which one is worth pursuing and implementing.

**Comment by jmaslek** [comment]
Think the number arg should be an int, not a float

Screen Shot 2021-11-17 at 3 11 28 PM

**Comment by jmaslek** [comment]
Screen Shot 2021-11-17 at 3 13 23 PM

**Comment by northern-64bit** [comment]
Everything should be fixed in the latest commit @jmaslek

**Comment by DidierRLopes** [comment]
Sorry for delay, I will try to have a look at this today.

**Comment by jmaslek** [comment]
Found another instance of the embedding object being shown.

Screen Shot 2021-11-19 at 10 13 02 AM

**Comment by jmaslek** [comment]
On the `gtrades` command as well:
Screen Shot 2021-11-19 at 10 15 05 AM

**Comment by northern-64bit** [comment]
> Found another instance of the embedding object being shown.
> 
> Screen Shot 2021-11-19 at 10 13 02 AM

This was fixed in the previous commit. I've now checked every file and after the latest commit there shouldn't be any emded errors. @jmaslek

**Comment by jmaslek** [comment]
> This was fixed in the previous commit. I've now checked every file and after the latest commit there shouldn't be any emded errors. @jmaslek

Weird.  VSCode PR extension is not actually refreshing

**Review by jmaslek — APPROVED** [review]

**Pull request merged**
