### PR TITLE
Dependency Audit

### PR DESCRIPTION
**Pull request by colin99d**
I ran through the current dependencies we have to see which ones were unused. It looks like the following were not needed:         
    - GitPython
    - sentiment-investor
    - pyrsistent
    - jsonschema

### CODE REVIEW

**Comment by colin99d** [comment]
@Chavithra and I already agreed to the test skip in my baseclass PR. Just adding this here so the tests pass.

**Comment by jmaslek** [comment]
Does the dps/volexch function work without dnspython?  I added it recently since it wasn't working without.  Also I think degiro-connector and pyally just get imported as different names...

**Comment by colin99d** [comment]
> dps/volexch

How do I find dps/volexch

**Comment by jmaslek** [comment]
> > dps/volexch
> 
> 
> 
> How do I find this.

stocks/dps

**Comment by colin99d** [comment]
> > > dps/volexch
> > 
> > 
> > How do I find this.
> 
> stocks/dps

You are right.

**Comment by jmaslek** [comment]
have you done through all the `gst` scripts and make sure the removed deps aren't hidden somewhere as a sub-dependency?

**Comment by aia** [comment]
Gitpython is used here:
https://github.com/GamestonkTerminal/GamestonkTerminal/blob/main/gamestonk_terminal/loggers.py#L10

**Comment by colin99d** [comment]
It looks like these are used just with other names. My mistake. Will close. Thanks for the reviews.

**Comment by aia** [comment]
This is a good though to keep an eye on used dependencies. Thank you Colin!

Even if we find out that all of our dependencies in use, regularly checks are important.

**Pull request closed without merging**
