### PR TITLE
Hotfix for jsondecode error in coinpaprika

### PR DESCRIPTION
**Pull request by jmaslek**
Address the failing tests by throwing the coinpaprika functions in a try block.

### CODE REVIEW

**Review by DidierRLopes — APPROVED** [review]
Looks good for now. Go ahead and merge.

An improvement is your suggestion of moving these code to inside the paprika_controller. So that it's only initialized when we go into that option.

**Comment by jmaslek** [comment]
> An improvement is your suggestion of moving these code to inside the paprika_controller. So that it's only initialized when we go into that option.

I agree.  But it is used with a check function so every time you would check a coin it would get redownloaded, so maybe @JakubPluta can do something clever.  This is mostly to block the tests from failing

**Comment by JakubPluta** [comment]
@jmaslek @DidierRLopes 

I am already in progress of restructuring whole crypto menu, so I will try to figure out something to load is just one. Maybe some cache or downloading data to a file (and simple check there if file exists load from file if no use api)

**Comment by jmaslek** [comment]
I agree that calling it once is the way to go.  Maybe they will update their API to avoid crashing more often.  

We could also just have a small file cached (could have GitHub run it daily and commit) that is loaded to compare with.

**Pull request merged**
