### PR TITLE
Degiro Integration : fixing issue with dependency

### PR DESCRIPTION
**Pull request by Chavithra**
Hi,

the following release was bugged : 
- `degiro-connnector`  0.1.1

I have released this version which fixed the issue : 
- `degiro-connnector` 0.1.3

`PR` #474 crashed when it tried to update to version `0.1.1`.

### CODE REVIEW

**Comment by DidierRLopes** [comment]
@aia with this the bug in #474 should be fixed. Is it ok to re-enable portfolio menu?

**Comment by aia** [comment]
> @aia with this the bug in #474 should be fixed. Is it ok to re-enable portfolio menu?

We still need to have clean imports. Looking at this code - https://github.com/GamestonkTerminal/GamestonkTerminal/blob/main/gamestonk_terminal/portfolio/degiro_model.py#L8 - it is impossible to tell where trading.helpers.payload_handler is coming from. External dependencies need to have imports matching the names of the dependencies.

**Comment by DidierRLopes** [comment]
> > @aia with this the bug in #474 should be fixed. Is it ok to re-enable portfolio menu?
> 
> We still need to have clean imports. Looking at this code - https://github.com/GamestonkTerminal/GamestonkTerminal/blob/main/gamestonk_terminal/portfolio/degiro_model.py#L8 - it is impossible to tell where trading.helpers.payload_handler is coming from. External dependencies need to have imports matching the names of the dependencies.

Got it! @Chavithra is it possible to refactor this in that way?

**Comment by aia** [comment]
> 
> 
> > > @aia with this the bug in #474 should be fixed. Is it ok to re-enable portfolio menu?
> > 
> > 
> > We still need to have clean imports. Looking at this code - https://github.com/GamestonkTerminal/GamestonkTerminal/blob/main/gamestonk_terminal/portfolio/degiro_model.py#L8 - it is impossible to tell where trading.helpers.payload_handler is coming from. External dependencies need to have imports matching the names of the dependencies.
> 
> Got it! @Chavithra is it possible to refactor this in that way?

It is very straight forward. Remember Didier, we had the same mistake in the early GamestonkTerminal?

https://github.com/GamestonkTerminal/GamestonkTerminal/tree/7afa86dc2d4e331581ebd00a66d1bca02f1c6296

You want to create a folder degiro_connector and move the rest of your code there.

**Comment by DidierRLopes** [comment]
> > > > @aia with this the bug in #474 should be fixed. Is it ok to re-enable portfolio menu?
> > > 
> > > 
> > > We still need to have clean imports. Looking at this code - https://github.com/GamestonkTerminal/GamestonkTerminal/blob/main/gamestonk_terminal/portfolio/degiro_model.py#L8 - it is impossible to tell where trading.helpers.payload_handler is coming from. External dependencies need to have imports matching the names of the dependencies.
> > 
> > 
> > Got it! @Chavithra is it possible to refactor this in that way?
> 
> It is very straight forward. Remember Didier, we had the same mistake in the early GamestonkTerminal?
> 
> https://github.com/GamestonkTerminal/GamestonkTerminal/tree/7afa86dc2d4e331581ebd00a66d1bca02f1c6296
> 
> You want to create a folder degiro_connector and move the rest of your code there.

Yes. I meant "Is it possible?" as in "Could you do that?"

**Comment by aia** [comment]
Also, I don;t know what happened to our requirements.txt, but it looks like this PR - https://github.com/GamestonkTerminal/GamestonkTerminal/pull/470 - broke builds in a pretty hardcore way - https://github.com/GamestonkTerminal/GamestonkTerminal/actions?query=is%3Acancelled.

Compare this  (build does not finish in 4 hours)- https://github.com/GamestonkTerminal/GamestonkTerminal/runs/2701605771?check_suite_focus=true

and this (build finishes in 11 minutes) - https://github.com/GamestonkTerminal/GamestonkTerminal/runs/2703431961?check_suite_focus=true

**Comment by DidierRLopes** [comment]
> Also, I don;t know what happened to our requirements.txt, but it looks like this PR - #467 - broke builds in a pretty hardcore way - https://github.com/GamestonkTerminal/GamestonkTerminal/actions?query=is%3Acancelled and https://github.com/GamestonkTerminal/GamestonkTerminal/actions/workflows/Mac.yml.
> 
> Compare this (build does not finish in 4 hours)- https://github.com/GamestonkTerminal/GamestonkTerminal/runs/2701605771?check_suite_focus=true
> 
> and this (build finishes in 11 minutes) - https://github.com/GamestonkTerminal/GamestonkTerminal/runs/2703431961?check_suite_focus=true

I think it may have been PR #463 actually. Should I revert the requirements.txt and requirements-full.txt to before that time? And just fix TimeSeriesCrossValidation pip install?

**Comment by aia** [comment]
> I think it may have been PR #463 actually. Should I revert the requirements.txt and requirements-full.txt to before that time? And just fix TimeSeriesCrossValidation pip install?

Requirements should be fine now.
What python/poetry versions are you using in your environment?

**Comment by Chavithra** [comment]
> > > > > @aia with this the bug in #474 should be fixed. Is it ok to re-enable portfolio menu?
> > > > 
> > > > 
> > > > We still need to have clean imports. Looking at this code - https://github.com/GamestonkTerminal/GamestonkTerminal/blob/main/gamestonk_terminal/portfolio/degiro_model.py#L8 - it is impossible to tell where trading.helpers.payload_handler is coming from. External dependencies need to have imports matching the names of the dependencies.
> > > 
> > > 
> > > Got it! @Chavithra is it possible to refactor this in that way?
> > 
> > 
> > It is very straight forward. Remember Didier, we had the same mistake in the early GamestonkTerminal?
> > https://github.com/GamestonkTerminal/GamestonkTerminal/tree/7afa86dc2d4e331581ebd00a66d1bca02f1c6296
> > You want to create a folder degiro_connector and move the rest of your code there.
> 
> Yes. I meant "Is it possible?" as in "Could you do that?"

Right now it's like my library is called "trading".

It is possible to change the naming and to put everything in a main module and I plan to do it.

But that will take some time specially because I need to build a migration script for project which already use it like that.

**Comment by DidierRLopes** [comment]
> > I think it may have been PR #463 actually. Should I revert the requirements.txt and requirements-full.txt to before that time? And just fix TimeSeriesCrossValidation pip install?
> 
> Requirements should be fine now.
> What python/poetry versions are you using in your environment?

I've been using Python 3.6.8 but I can update that. And Poetry version 1.1.5.

I can start using the latest.

**Comment by DidierRLopes** [comment]
> > > > > > @aia with this the bug in #474 should be fixed. Is it ok to re-enable portfolio menu?
> > > > > 
> > > > > 
> > > > > We still need to have clean imports. Looking at this code - https://github.com/GamestonkTerminal/GamestonkTerminal/blob/main/gamestonk_terminal/portfolio/degiro_model.py#L8 - it is impossible to tell where trading.helpers.payload_handler is coming from. External dependencies need to have imports matching the names of the dependencies.
> > > > 
> > > > 
> > > > Got it! @Chavithra is it possible to refactor this in that way?
> > > 
> > > 
> > > It is very straight forward. Remember Didier, we had the same mistake in the early GamestonkTerminal?
> > > https://github.com/GamestonkTerminal/GamestonkTerminal/tree/7afa86dc2d4e331581ebd00a66d1bca02f1c6296
> > > You want to create a folder degiro_connector and move the rest of your code there.
> > 
> > 
> > Yes. I meant "Is it possible?" as in "Could you do that?"
> 
> Right now it's like my library is called "trading".
> 
> It is possible to change the naming and to put everything in a main module and I plan to do it.
> 
> But that will take some time specially because I need to build a migration script for projects which already use it like that.

Should we then just comment degiro menu for the time being? Instead of the entire portfolio menu?

**Comment by aia** [comment]
> Should we then just comment degiro menu for the time being? Instead of the entire portfolio menu?

I already did that.

**Comment by DidierRLopes** [comment]
> > Should we then just comment degiro menu for the time being? Instead of the entire portfolio menu?
> 
> I already did that.

I think currently is the entire portfolio menu:
```
Portfolio Controller menu has been temporarily disabled
```

**Comment by aia** [comment]
> 
> 
> > > Should we then just comment degiro menu for the time being? Instead of the entire portfolio menu?
> > 
> > 
> > I already did that.
> 
> I think currently is the entire portfolio menu:
> 
> ```
> Portfolio Controller menu has been temporarily disabled
> ```

Oh. Looking at the portfolio menu I saw only Degiro enabled.
If there is a more elegant solution, that's great.

**Comment by Chavithra** [comment]
@aia :
Is it possible to enable Degiro sub-menu for the time being ?

Right now the integration of Degiro doesn't break anything.

The bug wasn't related to naming.

**Comment by aia** [comment]
> 
> 
> @aia :
> Is it possible to enable Degiro sub-menu for the time being ?
> 
> Right now the integration of Degiro doesn't break anything.
> 
> The bug wasn't related to naming.

The 0.1.3 version does fix linting.

Consider the question from the user's perspective. Would you want to use trading code that does not have clear module loading (test coverage and takes additional safety measures) and why?

**Review by aia — APPROVED** [review]

**Pull request merged**
