### PR TITLE
Fix to dcf command

### PR DESCRIPTION
**Pull request by colin99d**
This fix updates an issue where a company with less than 10 years of historical data would cause issues. @piiq I saw the issue with AA, but it ran issue free with TSLA. My best guess is that the source website had temporary issues. If you have more insight feel free to share and I can dig in.

### CODE REVIEW

**Comment by piiq** [comment]
Hey @JerBouma 👋
You've asked about DCF on discord. Can you check if this fix works for you?

**Review by DidierRLopes — APPROVED** [review]
Tested several tickers, all worked. I see numbers and an excel sheet, I'm happy 😄 

Before merging, can you add `dcf` to the row before `exit` on `scripts/test_stocks_fa.gst`?

**Review by piiq — CHANGES_REQUESTED** [review]
Hey! Thanks for the patch.

I've tested it with a number of tickers and the only one that failed was COIN
image
Can we have some feedback for the user if there was an error and no dcf sheet is being produced?

There is another problem that might only be visible to non-US ppl. The currencies in the XLS are local, what leads to spreadsheets like this
image

Can you explicitly set the currency type of the cells when you create the spreadsheet? Either the actual currency or USD if the data source is only in USD.

**Comment by colin99d** [comment]
> Hey! Thanks for the patch.
> 
> I've tested it with a number of tickers and the only one that failed was COIN image Can we have some feedback for the user if there was an error and no dcf sheet is being produced?
> 
> There is another problem that might only be visible to non-US ppl. The currencies in the XLS are local, what leads to spreadsheets like this image
> 
> Can you explicitly set the currency type of the cells when you create the spreadsheet? Either the actual currency or USD if the data source is only in USD.

Looking into the currency issue right now. Also, COIN ran fine for me.

**Comment by piiq** [comment]
> COIN ran fine for me.

On my end this was some issue with "sister companies" if I understand correctly.

**Comment by colin99d** [comment]
> > COIN ran fine for me.
> 
> On my end this was some issue with "sister companies" if I understand correctly.

I see. For now I am just printing an error message. In the future this should just cause the excel to not have ratios. I will work on better error handling in the future.

**Comment by DidierRLopes** [comment]
Let's merge this for now! It's @JerBouma birthday, so this will make him happy eheheh Let's go 🚀

**Review by DidierRLopes — APPROVED** [review]

**Comment by DidierRLopes** [comment]
Needs @piiq approval 😬

**Comment by piiq** [comment]
Thanks for addressing the issues @colin99d
image
Great job!

**Review by piiq — APPROVED** [review]

**Pull request merged**
