### PR TITLE
Global plot styles

### PR DESCRIPTION
**Pull request by piiq**
# Description

This PR introduces global stylesheet management for MPL, MPF and Rich. By default the terminal has 2 styles:

Light:
image

Dark:
image

The dark style is default.

The styles go into the `styles` folder (surprise!). The `styles/user` folder is ignored by git and everyone is encouraged to pus custom styles there.

# How has this been tested?

Generated TA charts with `test_stocks_ta.gst` (see comment bellow)

---

Context checklist:

- [x] alternative (Theo)
- [x] common (Theo)
- [x] cryptocurrency (Minh)
- [x] custom (James)
- [x] economy (Colin)
- [x] etf (Colin)
- [x] forex (Theo)
- [x] mutual_funds (James)
- [x] options (Colin)
- [x] portfolio (James)
- [x] resources
- [x] stocks (Minh)

### CODE REVIEW

**Review by DidierRLopes — COMMENTED** [review]
This looks good, my comments are:
* Implement this for all TA functions
* Have a similar styling being implemented to matplotlib globally (however, not sure you want this to be part of the scope of this PR)

**Comment by jmaslek** [comment]
I agree with @DidierRLopes.  Additionally it would be good to see what some of the other plots you styled look like (bars/pies/..). as well as a sample maybe from Fred that shows different multiple plots overlayed.

**Comment by piiq** [comment]
This PR was updated with newer stylesheets and the style helper. The default style is `dark`

The styles were applied to all common ta charts.
Here's how it looks

https://user-images.githubusercontent.com/11668535/151452086-2ba46d7a-ebeb-4a77-969b-c95d17cb3ad6.mp4


Tested the functionality with `test_stocks_ta.gst` script

**Comment by minhhoang1023** [comment]
@piiq Wow! Was trying out the TA commands and the graphs look so good and professional! ✨ Really love the styling.

Some very small comments:

- Would it be possible to have the first ticker's label on the x-axis? You have probably thought about it and decided to take it out, as it might make the graph bigger. It's useful though to know where the starting date of the graph. 

Screenshot 2022-01-31 at 11 08 20

- Is there any rule on when we should apply the up vs down color? As in this particular case, I felt that the color order should be reversed - so blue on top and red on the bottom.
image

I was trying hard to find anything to improve but really that's all I can find. It looks perfect! Amazing work!

**Comment by piiq** [comment]
This PR relates to this https://github.com/GamestonkTerminal/GamestonkTerminal/projects/10#card-74305818

**Pull request merged**
