### PR TITLE
Added ReadMe for Tests

### PR DESCRIPTION
**Pull request by colin99d**
Added a ReadMe to make creating tests easier. This includes using the tools pytest, coverage, vcrpy, and a custom decorator check_print.

### CODE REVIEW

**Comment by DidierRLopes** [comment]
What do you think about adding this on CONTRIBUTING.md document in #660 ?

**Comment by colin99d** [comment]
> What do you think about adding this on CONTRIBUTING.md document in #660 ?

Sounds good to me. Do you want me to close this repo and then once #660 gets merged I can reopen with this PR?

**Comment by DidierRLopes** [comment]
You can leave it open, and once 660 is merged, we can merge them?

**Comment by colin99d** [comment]
Perfect!

**Comment by DidierRLopes** [comment]
#660 merged, so you can add this there :)

**Review by DidierRLopes — APPROVED** [review]
Perfect :)

**Review by DidierRLopes — APPROVED** [review]

**Pull request merged**
