### PR TITLE
Feature (crypto): Altcoin season index

### PR DESCRIPTION
**Pull request by jose-donato**
Introduces new crypto feature to `ov` crypto menu: Altcoin season index from [Blockchain Center Source](https://www.blockchaincenter.net/altcoin-season-index/)

Example:
`altindex --period 365`
image

Checks whether 75% of the Top 50 coins performed better than Bitcoin over the last year (365 days). If so, it is considered alt coin season.

### CODE REVIEW

**Review by jmaslek — CHANGES_REQUESTED** [review]
You help strings are not consistent:

```
  -s SINCE, --since SINCE
                        Initial date. Default: 2020-01-01 (default: 2021-01-07)
  -u UNTIL, --until UNTIL
                        Final date. E.g.,: 2021-01-01 (default: 2022-01-07)
```

Maybe add the grid and print a newline at the end of the command.

**Comment by jose-donato** [comment]
> You help strings are not consistent:
> 
> ```
>   -s SINCE, --since SINCE
>                         Initial date. Default: 2020-01-01 (default: 2021-01-07)
>   -u UNTIL, --until UNTIL
>                         Final date. E.g.,: 2021-01-01 (default: 2022-01-07)
> ```
> 
> Maybe add the grid and print a newline at the end of the command.

ooopsy will fix it

**Review by jmaslek — APPROVED** [review]
Once the tests pass

**Comment by jose-donato** [comment]
```ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\Users\\runneradmin\\AppData\\Local\\Temp\\pip-uninstall-wbtwai5k\\pygmentize.exe'```

@jmaslek it is failing on the last test. do you know what the problem is?

**Comment by jmaslek** [comment]
No idea. Since it's not on your end feel free to merge

**Comment by jose-donato** [comment]
> No idea. Since it's not on your end feel free to merge

the other PR with bitcoin rainbow is also failing on this. @piiq any idea what is happening here?

**Comment by piiq** [comment]
> > No idea. Since it's not on your end feel free to merge
> 
> the other PR with bitcoin rainbow is also failing on this. @piiq any idea what is happening here?

@jose-donato The deps are out of sync. I guess merging main into this branch to sync dependencies may help

**Comment by jmaslek** [comment]
> > > No idea. Since it's not on your end feel free to merge
> > 
> > 
> > the other PR with bitcoin rainbow is also failing on this. @piiq any idea what is happening here?
> 
> @jose-donato The deps are out of sync. I guess merging main into this branch to sync dependencies may help

im gonna do it

**Comment by jose-donato** [comment]
> > > No idea. Since it's not on your end feel free to merge
> > 
> > 
> > the other PR with bitcoin rainbow is also failing on this. @piiq any idea what is happening here?
> 
> @jose-donato The deps are out of sync. I guess merging main into this branch to sync dependencies may help

thanks!

**Pull request merged**
